import type { Menu, MenuItem, MenuSection } from "@/lib/types";

/**
 * Food photo pool — Unsplash IDs verified returning 200 at time of seed.
 * Grouped loosely by cuisine so we can reuse across restaurants without
 * feeling stock-generic.
 */
const P = {
  // Romanian / stews / comfort
  stew: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&h=400&fit=crop",
  sarmale: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop",
  mici: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
  papanasi: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",

  // Italian
  carbonara: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&h=400&fit=crop",
  pasta: "https://images.unsplash.com/photo-1485921325833-c519f76c4927?w=600&h=400&fit=crop",
  ragu: "https://images.unsplash.com/photo-1559339352-11d035aa65de?w=600&h=400&fit=crop",
  pizza: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&h=400&fit=crop",
  tiramisu: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&h=400&fit=crop",
  bruschetta: "https://images.unsplash.com/photo-1470337458703-46ad1756a187?w=600&h=400&fit=crop",

  // Japanese
  sushiPlatter: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&h=400&fit=crop",
  sashimi: "https://images.unsplash.com/photo-1553621042-f6e147245754?w=600&h=400&fit=crop",
  rolls: "https://images.unsplash.com/photo-1540648639573-8c848de23f0a?w=600&h=400&fit=crop",
  nigiri: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=600&h=400&fit=crop",
  sushiBoard: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
  sashimi2: "https://images.unsplash.com/photo-1481931098730-318b6f776db0?w=600&h=400&fit=crop",
  ramen: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=400&fit=crop",

  // French / fine dining
  steak: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=600&h=400&fit=crop",
  plated: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
  fineDining: "https://images.unsplash.com/photo-1530554764233-e79e16c91d08?w=600&h=400&fit=crop",
  dessertPlated: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=600&h=400&fit=crop",

  // Asian / general
  asian: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop",
  wok: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=600&h=400&fit=crop",
  dumplings: "https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?w=600&h=400&fit=crop",

  // Breakfast / pastry
  pastry: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&h=400&fit=crop",

  // Misc / generic
  tapas: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",

  // Drinks
  wineRed: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&h=400&fit=crop",
  wineGlass: "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=600&h=400&fit=crop",
  cocktail: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&h=400&fit=crop",
  beer: "https://images.unsplash.com/photo-1608270586620-248524c67de9?w=600&h=400&fit=crop",
  espresso: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&h=400&fit=crop",
  tea: "https://images.unsplash.com/photo-1594631252845-29fc4cc8cde9?w=600&h=400&fit=crop",
};

function makeMenu(
  restaurantId: string,
  heroNote: string,
  sections: MenuSection[],
  items: Omit<MenuItem, "id">[],
  currency: Menu["currency"] = "lei",
): Menu {
  return {
    restaurantId,
    currency,
    sections,
    heroNote,
    items: items.map((it, i) => ({ ...it, id: `${restaurantId}-${i}` })),
  };
}

// Reusable drink sections keyed by cuisine
const drinksIntros = {
  ro: "Romanian wines, țuică that grandmothers warn you about, and a few local classics.",
  it: "Italian regional wines, digestivi, and one well-made espresso.",
  jp: "Sake by the carafe, Japanese whisky by the glass, green tea always.",
  fr: "A short list of French wines, one aperitif, one digestif.",
  tr: "Rakı with mezze, çay at any hour, and everything in between.",
  cn: "Chinese rice wine, tea by the pot, and a cold Tsingtao.",
  es: "Rioja, cava, sangría by the jug.",
  in: "Lassi, masala chai, and a Kingfisher when the curry gets hot.",
  us: "Craft beers, bourbon cocktails, and a proper milkshake.",
  lb: "Arak, Lebanese wine, fresh mint lemonade.",
  th: "Thai beers, iced tea, and coconut water.",
  gr: "Ouzo, assyrtiko, and metaxa for after.",
  ko: "Soju shared in small glasses — the Korean way.",
  mx: "Tequila, mezcal, and horchata for those who don't.",
  bk: "Rakija first, beer with the food, espresso after.",
};

const menus: Record<string, Menu> = {
  "casa-veche": makeMenu(
    "1",
    "Grandmother's recipes from the heart of Centru Vechi. Cooked slow, served warm.",
    [
      { id: "aperitive", name: "Aperitive", intro: "Small plates to warm up the table — the way every Romanian meal begins." },
      { id: "ciorbe", name: "Ciorbe & Supe", intro: "Sour soups, slow broths. Start with a spoon before anything else arrives." },
      { id: "principale", name: "Feluri principale", intro: "Grandmother's recipes, barely updated." },
      { id: "deserturi", name: "Deserturi", intro: "Sweet endings from the Carpathians to the Black Sea." },
      { id: "bauturi", name: "Băuturi & Vinuri", intro: drinksIntros.ro },
    ],
    [
      { sectionId: "aperitive", name: "Zacuscă de casă", description: "Roasted pepper & aubergine spread, served with grandma's homemade bread.", price: 24, photoUrl: P.bruschetta, tags: ["vegetarian"] },
      { sectionId: "aperitive", name: "Salată de vinete", description: "Smoky aubergine salad with sweet onion and house olive oil.", price: 22, tags: ["vegetarian", "vegan"] },
      { sectionId: "aperitive", name: "Mămăligă cu brânză și smântână", description: "Buttery polenta with sheep's cheese and sour cream.", price: 28, photoUrl: P.plated, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "aperitive", name: "Platou de brânzeturi românești", description: "Telemea, caș, brânză de burduf and urdă with walnut honey.", price: 42, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "ciorbe", name: "Ciorbă de burtă", description: "Classic tripe soup soured with borș, finished with garlic cream and chilli vinegar on the side.", price: 32, photoUrl: P.stew, tags: ["popular"] },
      { sectionId: "ciorbe", name: "Ciorbă rădăuțeană", description: "Creamy chicken & vegetable soup from Bukovina, with sour cream and egg.", price: 28 },
      { sectionId: "ciorbe", name: "Ciorbă de perișoare", description: "Sour meatball soup with lovage and tarragon.", price: 26 },
      { sectionId: "principale", name: "Sarmale în foi de viță", description: "Grandmother's recipe — pork & rice wrapped in pickled vine leaves, served with mămăligă and sour cream.", price: 58, photoUrl: P.sarmale, tags: ["chef-pick", "popular"] },
      { sectionId: "principale", name: "Mici cu muștar", description: "Five skinless grilled beef & lamb sausages, Romanian mustard, pickled chillies.", price: 48, photoUrl: P.mici, tags: ["popular"] },
      { sectionId: "principale", name: "Tochitură moldovenească", description: "Slow-braised pork in smoked-paprika gravy, mămăligă, fried egg, telemea cheese.", price: 62, photoUrl: P.stew, tags: ["chef-pick"] },
      { sectionId: "principale", name: "Ciolan de porc la cuptor", description: "Roast pork knuckle on a bed of sauerkraut and beans, hot mustard.", price: 68, photoUrl: P.steak },
      { sectionId: "principale", name: "Friptură de miel", description: "Rosemary-roasted lamb shoulder with young potatoes and pan jus.", price: 84 },
      { sectionId: "deserturi", name: "Papanași cu smântână și dulceață de vișine", description: "Warm ricotta doughnuts, sour cream, sour-cherry jam.", price: 28, photoUrl: P.papanasi, tags: ["chef-pick", "popular", "vegetarian"] },
      { sectionId: "deserturi", name: "Plăcintă cu mere", description: "Flaky apple pie with cinnamon, served warm with vanilla ice cream.", price: 24, photoUrl: P.pastry, tags: ["vegetarian"] },
      { sectionId: "deserturi", name: "Cozonac cu nucă", description: "Sweet braided bread with walnut filling, toasted at the table.", price: 22, tags: ["vegetarian"] },
      { sectionId: "bauturi", name: "Fetească Neagră (pahar)", description: "Romania's flagship red — plum, black cherry, soft tannin.", price: 38, photoUrl: P.wineRed },
      { sectionId: "bauturi", name: "Fetească Regală (pahar)", description: "Crisp Romanian white, citrus and green apple.", price: 28 },
      { sectionId: "bauturi", name: "Țuică de prune", description: "Traditional plum brandy, 40%. Served cold.", price: 22 },
      { sectionId: "bauturi", name: "Vișinată", description: "House sour-cherry liqueur, slow-steeped.", price: 18 },
      { sectionId: "bauturi", name: "Ursus Premium", description: "Romanian pilsner, draft.", price: 14, photoUrl: P.beer },
      { sectionId: "bauturi", name: "Socată", description: "Fermented elderflower lemonade, house-made.", price: 16, tags: ["popular"] },
    ],
  ),

  "la-mama": makeMenu(
    "18",
    "Classic Romanian comfort food. Big plates, bigger portions.",
    [
      { id: "starters", name: "Pentru început", intro: "A little something to share before the grill arrives." },
      { id: "ciorbe", name: "Ciorbe", intro: "Every proper Romanian meal starts with a soup. Don't skip it." },
      { id: "grill", name: "De pe grătar", intro: "From the charcoal grill — where the kitchen actually lives." },
      { id: "deserturi", name: "Deserturi", intro: "Papanași, mostly. Everything else is decoration." },
      { id: "bauturi", name: "Băuturi", intro: drinksIntros.ro },
    ],
    [
      { sectionId: "starters", name: "Salată cu brânză și roșii", description: "Telemea, sweet heirloom tomatoes, red onion, oregano.", price: 26, photoUrl: P.bruschetta, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "starters", name: "Pastrama afumată", description: "House-smoked lamb pastrama, horseradish, rye bread.", price: 38, photoUrl: P.plated },
      { sectionId: "starters", name: "Jumări cu ceapă", description: "Crispy pork cracklings with pickled onions and mustard.", price: 28 },
      { sectionId: "ciorbe", name: "Ciorbă de legume", description: "Garden-vegetable sour soup with a spoon of sour cream.", price: 22, tags: ["vegetarian"] },
      { sectionId: "ciorbe", name: "Ciorbă de pui cu tăieței", description: "Clear chicken broth with homemade egg noodles.", price: 24, photoUrl: P.stew },
      { sectionId: "grill", name: "Mici (10 buc)", description: "Ten grilled beef-lamb mici, mustard, pickled chillies.", price: 65, photoUrl: P.mici, tags: ["popular"] },
      { sectionId: "grill", name: "Cotlet de porc la grătar", description: "Grill-marked pork chop, garlic-roasted potatoes, grilled peppers.", price: 58, photoUrl: P.steak },
      { sectionId: "grill", name: "Pulpă de pui la grătar", description: "Char-grilled chicken leg with lemon and mămăligă.", price: 42 },
      { sectionId: "grill", name: "Platou mixt", description: "Mixed grill for two — mici, chicken, pork, sausage.", price: 145, photoUrl: P.mici, tags: ["chef-pick"] },
      { sectionId: "deserturi", name: "Papanași", description: "House ricotta doughnuts, smântână, sour-cherry jam.", price: 26, photoUrl: P.papanasi, tags: ["popular", "vegetarian"] },
      { sectionId: "deserturi", name: "Clătite cu dulceață", description: "Thin pancakes with plum jam.", price: 22, tags: ["vegetarian"] },
      { sectionId: "bauturi", name: "Fetească Neagră (pahar)", description: "Romanian red, plum and black cherry.", price: 34, photoUrl: P.wineRed },
      { sectionId: "bauturi", name: "Țuică de prune", description: "Plum brandy, 40%.", price: 20 },
      { sectionId: "bauturi", name: "Ciuc Premium", description: "Romanian pilsner.", price: 12, photoUrl: P.beer },
      { sectionId: "bauturi", name: "Limonadă cu mentă", description: "Fresh lemon, mint, sparkling.", price: 14, tags: ["popular"] },
    ],
  ),

  "sakura-sushi": makeMenu(
    "2",
    "Morning's market, afternoon's knife, evening's counter. Precise, restrained, honest.",
    [
      { id: "starters", name: "Starters", intro: "Small plates to ease into the meal." },
      { id: "sashimi", name: "Sashimi", intro: "Morning's market, sliced to order." },
      { id: "nigiri", name: "Nigiri", intro: "Hand-pressed, lightly dressed. Eat in one bite." },
      { id: "rolls", name: "Rolls", intro: "Where tradition and invention meet." },
      { id: "mains", name: "Mains", intro: "When sushi isn't enough." },
      { id: "drinks", name: "Drinks & Sake", intro: drinksIntros.jp },
    ],
    [
      { sectionId: "starters", name: "Edamame", description: "Steamed soybeans, Maldon salt.", price: 22, tags: ["vegan", "vegetarian", "gluten-free"] },
      { sectionId: "starters", name: "Gyoza (6pc)", description: "Pan-fried pork & ginger dumplings, soy-vinegar dipping sauce.", price: 38, photoUrl: P.dumplings },
      { sectionId: "starters", name: "Chicken karaage", description: "Japanese fried chicken, spicy kewpie mayo.", price: 36, photoUrl: P.asian },
      { sectionId: "starters", name: "Miso soup", description: "Dashi, silken tofu, wakame, scallion.", price: 18, tags: ["vegetarian"] },
      { sectionId: "sashimi", name: "Salmon sashimi (6pc)", description: "Thick-cut Norwegian salmon belly.", price: 58, photoUrl: P.sashimi },
      { sectionId: "sashimi", name: "Tuna sashimi (6pc)", description: "Line-caught bluefin, shiso, radish.", price: 72, photoUrl: P.sashimi2, tags: ["chef-pick"] },
      { sectionId: "sashimi", name: "Yellowtail sashimi (6pc)", description: "Hamachi, yuzu kosho, chive oil.", price: 68 },
      { sectionId: "nigiri", name: "Omakase nigiri (8pc)", description: "Chef's selection of the morning market — tuna, salmon, hamachi, ebi, unagi, ikura and two surprises.", price: 135, photoUrl: P.nigiri, tags: ["chef-pick", "popular"] },
      { sectionId: "nigiri", name: "Otoro nigiri (2pc)", description: "Fatty tuna belly, soy tare brushed at the pass.", price: 58, photoUrl: P.sushiBoard, tags: ["chef-pick"] },
      { sectionId: "rolls", name: "Dragon roll", description: "Unagi, cucumber, avocado, eel sauce.", price: 62, photoUrl: P.rolls, tags: ["popular"] },
      { sectionId: "rolls", name: "Spicy tuna roll", description: "Tuna, spring onion, chilli mayo, sesame.", price: 48, tags: ["spicy"] },
      { sectionId: "rolls", name: "Rainbow roll", description: "California roll topped with tuna, salmon, yellowtail and avocado.", price: 68, photoUrl: P.sushiPlatter },
      { sectionId: "rolls", name: "Tempura prawn roll", description: "Ebi tempura, cucumber, avocado, spicy mayo.", price: 54 },
      { sectionId: "mains", name: "Chirashi bowl", description: "Seasonal cuts of sashimi over sushi rice, pickles, tamago.", price: 88, photoUrl: P.sushiPlatter },
      { sectionId: "mains", name: "Wagyu tataki", description: "Seared A5 wagyu, ponzu, crispy garlic, micro shiso.", price: 145, photoUrl: P.steak, tags: ["chef-pick"] },
      { sectionId: "mains", name: "Tonkatsu set", description: "Panko-crusted pork loin, tonkatsu sauce, rice, miso, pickles.", price: 72 },
      { sectionId: "drinks", name: "Daiginjo sake (carafe)", description: "Premium, floral, cold.", price: 145, photoUrl: P.wineGlass, tags: ["chef-pick"] },
      { sectionId: "drinks", name: "Junmai sake (carafe)", description: "Clean, dry, served chilled or warm.", price: 95 },
      { sectionId: "drinks", name: "Asahi Super Dry", description: "Japanese lager, draft.", price: 26, photoUrl: P.beer },
      { sectionId: "drinks", name: "Plum wine (umeshu)", description: "Sweet, on the rocks.", price: 32 },
      { sectionId: "drinks", name: "Sencha (pot)", description: "Premium Japanese green tea.", price: 22, photoUrl: P.tea },
      { sectionId: "drinks", name: "Yuzu highball", description: "Japanese whisky, yuzu soda.", price: 38 },
    ],
  ),

  "trattoria-roma": makeMenu(
    "3",
    "Roman cooking, unfussed. Guanciale not bacon. No cream in the carbonara.",
    [
      { id: "antipasti", name: "Antipasti", intro: "Small bites to share while the primi is still cooking." },
      { id: "primi", name: "Primi Piatti", intro: "Pasta, risotto, soup. Always the first real course." },
      { id: "secondi", name: "Secondi", intro: "What follows the primi. Meat or fish, then linger." },
      { id: "dolci", name: "Dolci", intro: "A sweet pause before espresso." },
      { id: "vini", name: "Vini & Bevande", intro: drinksIntros.it },
    ],
    [
      { sectionId: "antipasti", name: "Burrata Pugliese", description: "Creamy burrata, San Marzano tomatoes, basil, Amalfi lemon oil.", price: 48, photoUrl: P.plated, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "antipasti", name: "Prosciutto & melone", description: "18-month Parma ham with Sicilian melon.", price: 52, photoUrl: P.bruschetta, tags: ["gluten-free"] },
      { sectionId: "antipasti", name: "Bruschetta al pomodoro", description: "Toasted sourdough, heirloom tomatoes, garlic, basil.", price: 32, tags: ["vegetarian", "vegan"] },
      { sectionId: "antipasti", name: "Carpaccio di manzo", description: "Aged beef, rocket, parmigiano, truffle oil.", price: 56, photoUrl: P.steak },
      { sectionId: "primi", name: "Spaghetti alla Carbonara", description: "Guanciale, pecorino romano, egg yolk, black pepper. No cream, ever.", price: 58, photoUrl: P.carbonara, tags: ["popular"] },
      { sectionId: "primi", name: "Cacio e Pepe", description: "Handmade tonnarelli, Lazio pecorino, four-pepper blend.", price: 54, photoUrl: P.pasta, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "primi", name: "Tagliatelle al ragù Bolognese", description: "Slow-cooked beef & pork ragù, fresh tagliatelle.", price: 62, photoUrl: P.ragu, tags: ["popular"] },
      { sectionId: "primi", name: "Risotto ai funghi porcini", description: "Carnaroli rice, porcini, thyme butter, aged parmigiano.", price: 66, photoUrl: P.pasta, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "primi", name: "Lasagne alla Bolognese", description: "Seven-layer lasagne, béchamel, 6-hour ragù.", price: 64 },
      { sectionId: "secondi", name: "Saltimbocca alla Romana", description: "Veal escalope, prosciutto, sage, white wine jus.", price: 88, photoUrl: P.plated, tags: ["chef-pick"] },
      { sectionId: "secondi", name: "Osso buco con gremolata", description: "Braised veal shank, saffron risotto Milanese, lemon-parsley gremolata.", price: 118, photoUrl: P.steak },
      { sectionId: "secondi", name: "Branzino al sale", description: "Whole sea bass baked in salt, cracked tableside, olive oil & lemon.", price: 145, photoUrl: P.fineDining, tags: ["gluten-free"] },
      { sectionId: "dolci", name: "Tiramisu della casa", description: "Savoiardi, mascarpone, espresso, cocoa. Made in-house every morning.", price: 34, photoUrl: P.tiramisu, tags: ["popular", "vegetarian"] },
      { sectionId: "dolci", name: "Panna cotta ai frutti di bosco", description: "Vanilla-bean panna cotta, wild berry coulis.", price: 32, photoUrl: P.dessertPlated, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "dolci", name: "Cannoli siciliani", description: "Crisp shells, sweet ricotta, pistachio, candied orange.", price: 30, tags: ["vegetarian"] },
      { sectionId: "dolci", name: "Affogato", description: "Vanilla gelato drowned in hot espresso, optional shot of amaro.", price: 26, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "vini", name: "Chianti Classico (glass)", description: "Tuscan red, cherry, leather, long finish.", price: 45, photoUrl: P.wineRed },
      { sectionId: "vini", name: "Prosecco DOC (flute)", description: "Glera sparkling, crisp and clean.", price: 38, photoUrl: P.wineGlass },
      { sectionId: "vini", name: "Aperol Spritz", description: "Aperol, Prosecco, soda, orange.", price: 34, photoUrl: P.cocktail, tags: ["popular"] },
      { sectionId: "vini", name: "Negroni", description: "Campari, sweet vermouth, London dry gin.", price: 38, photoUrl: P.cocktail },
      { sectionId: "vini", name: "Limoncello della casa", description: "House digestivo, ice-cold.", price: 18 },
      { sectionId: "vini", name: "Espresso", description: "Single shot, Italian roast.", price: 12, photoUrl: P.espresso },
    ],
  ),

  "pizzeria-napoli": makeMenu(
    "11",
    "Wood-fired pizza, 90 seconds at 430°C. Neapolitan dough, Roman pace.",
    [
      { id: "antipasti", name: "Antipasti", intro: "A few small bites before the oven does its thing." },
      { id: "pizza", name: "Pizza", intro: "From our wood-fired oven — 90 seconds at 430°C." },
      { id: "pasta", name: "Pasta", intro: "Fresh daily. No shortcuts." },
      { id: "dolci", name: "Dolci", intro: "Sweet, quick, to be eaten standing up." },
      { id: "drinks", name: "Bevande", intro: drinksIntros.it },
    ],
    [
      { sectionId: "antipasti", name: "Bruschetta classica", description: "Toasted bread, tomato, basil, garlic.", price: 22, photoUrl: P.bruschetta, tags: ["vegetarian", "vegan"] },
      { sectionId: "antipasti", name: "Insalata caprese", description: "Buffalo mozzarella, tomatoes, basil, olive oil.", price: 28, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "antipasti", name: "Arancini (3pc)", description: "Crispy risotto balls stuffed with ragù and mozzarella.", price: 26, photoUrl: P.dumplings },
      { sectionId: "pizza", name: "Margherita DOP", description: "San Marzano tomato, buffalo mozzarella, basil, extra virgin olive oil.", price: 38, photoUrl: P.pizza, tags: ["vegetarian", "popular"] },
      { sectionId: "pizza", name: "Diavola", description: "Tomato, mozzarella, spicy salame Calabrese, chilli oil.", price: 42, photoUrl: P.pizza, tags: ["spicy", "popular"] },
      { sectionId: "pizza", name: "Quattro Formaggi", description: "Mozzarella, gorgonzola, parmigiano, pecorino.", price: 44, tags: ["vegetarian"] },
      { sectionId: "pizza", name: "Prosciutto e Funghi", description: "Tomato, mozzarella, cooked ham, mushroom.", price: 42 },
      { sectionId: "pizza", name: "Capricciosa", description: "Tomato, mozzarella, ham, mushroom, artichoke, olives.", price: 46 },
      { sectionId: "pizza", name: "Tartufo nero", description: "Fior di latte, black truffle cream, porcini, parmigiano.", price: 58, photoUrl: P.pizza, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "pasta", name: "Spaghetti aglio e olio", description: "Garlic, chilli, extra virgin olive oil, parsley.", price: 32, photoUrl: P.pasta, tags: ["vegan", "spicy"] },
      { sectionId: "pasta", name: "Penne all'arrabbiata", description: "Spicy tomato sauce, garlic, chilli, basil.", price: 34, tags: ["vegan", "spicy"] },
      { sectionId: "dolci", name: "Tiramisu", description: "House tiramisu, dusted cocoa.", price: 18, photoUrl: P.tiramisu, tags: ["vegetarian"] },
      { sectionId: "dolci", name: "Cannoli (2pc)", description: "Sweet ricotta, pistachio.", price: 16, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Peroni Nastro Azzurro", description: "Italian pilsner, cold.", price: 14, photoUrl: P.beer },
      { sectionId: "drinks", name: "Montepulciano (glass)", description: "Honest Italian red, easy-going.", price: 28, photoUrl: P.wineRed },
      { sectionId: "drinks", name: "Pinot Grigio (glass)", description: "Light, fresh, mineral.", price: 26 },
      { sectionId: "drinks", name: "Limoncello", description: "Chilled, to finish.", price: 14 },
      { sectionId: "drinks", name: "Espresso", description: "Italian roast, single shot.", price: 10, photoUrl: P.espresso, tags: ["popular"] },
    ],
  ),

  "ristorante-milano": makeMenu(
    "19",
    "Piedmontese beef, Alba truffle in season, Normandy oysters. Old-world fine dining on the Aviatorilor end.",
    [
      { id: "antipasti", name: "Antipasti", intro: "Classical Italian openers, executed with precision." },
      { id: "primi", name: "Primi Piatti", intro: "Risotto in Alba truffle season. Linguine when the lobster is right." },
      { id: "secondi", name: "Secondi", intro: "The centrepiece. Order generously, share freely." },
      { id: "dolci", name: "Dolci", intro: "Desserts as theatre — soufflés, tiramisu laced with Marsala." },
      { id: "vini", name: "Vini & Digestivi", intro: drinksIntros.it },
    ],
    [
      { sectionId: "antipasti", name: "Vitello tonnato", description: "Thin-sliced veal, tuna-caper emulsion, fried capers.", price: 82, photoUrl: P.plated, tags: ["chef-pick"] },
      { sectionId: "antipasti", name: "Carpaccio al tartufo", description: "Aged Piedmontese beef, shaved black truffle, 24-month parmigiano.", price: 95, photoUrl: P.steak, tags: ["chef-pick"] },
      { sectionId: "antipasti", name: "Ostriche fines de claire (3)", description: "Three Normandy oysters, lemon, mignonette.", price: 88, tags: ["gluten-free"] },
      { sectionId: "primi", name: "Risotto al tartufo", description: "Acquerello rice, white Alba truffle in season, butter, parmigiano.", price: 165, photoUrl: P.pasta, tags: ["chef-pick", "vegetarian"] },
      { sectionId: "primi", name: "Tortelli di zucca", description: "Pumpkin-stuffed tortelli, amaretti, sage butter, mostarda.", price: 125, photoUrl: P.pasta, tags: ["vegetarian", "popular"] },
      { sectionId: "primi", name: "Linguine all'astice", description: "Fresh linguine, whole Breton lobster, cherry tomato, basil.", price: 215, photoUrl: P.fineDining },
      { sectionId: "secondi", name: "Bistecca alla Fiorentina", description: "Dry-aged T-bone for two, grilled over oak, rosemary oil, sea salt.", price: 238, photoUrl: P.steak, tags: ["chef-pick", "popular"] },
      { sectionId: "secondi", name: "Ossobuco con risotto", description: "Slow-braised veal shank, Milanese saffron risotto.", price: 185, photoUrl: P.stew },
      { sectionId: "secondi", name: "Branzino al sale di Maldon", description: "Whole line-caught branzino, salt-crust, Amalfi lemon.", price: 195, photoUrl: P.fineDining, tags: ["gluten-free"] },
      { sectionId: "dolci", name: "Tiramisu al Marsala", description: "House tiramisu laced with 10-year Marsala, hand-whipped tableside.", price: 52, photoUrl: P.tiramisu, tags: ["vegetarian"] },
      { sectionId: "dolci", name: "Soufflé al cioccolato", description: "Valrhona chocolate soufflé, vanilla ice cream. 20 minutes.", price: 58, photoUrl: P.dessertPlated, tags: ["vegetarian"] },
      { sectionId: "dolci", name: "Selezione di formaggi italiani", description: "Seven Italian cheeses, truffle honey, fig mostarda.", price: 72, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "vini", name: "Barolo 10-year (glass)", description: "Nebbiolo, rose, tar, structure.", price: 95, photoUrl: P.wineRed },
      { sectionId: "vini", name: "Brunello di Montalcino", description: "Sangiovese grosso, cherry, leather.", price: 85 },
      { sectionId: "vini", name: "Franciacorta (flute)", description: "Italy's answer to champagne.", price: 65, photoUrl: P.wineGlass },
      { sectionId: "vini", name: "Grappa di Barolo", description: "12-year, to finish.", price: 48 },
    ],
  ),

  "sultan-kebab": makeMenu(
    "4",
    "Hand-chopped lamb, charcoal grill, bread straight from the oven. Istanbul on Strada Obor.",
    [
      { id: "mezeler", name: "Mezeler", intro: "A table full of small dishes — the heart of Turkish dining." },
      { id: "kebaplar", name: "Kebaplar", intro: "From the charcoal grill. Smoke, fat, fire." },
      { id: "pideler", name: "Pideler", intro: "Turkey's boat-shaped flatbreads, stone-oven baked." },
      { id: "tatlilar", name: "Tatlılar", intro: "Sweet endings, pistachios included." },
      { id: "icecekler", name: "İçecekler", intro: drinksIntros.tr },
    ],
    [
      { sectionId: "mezeler", name: "Hummus", description: "Smooth chickpea purée, tahini, olive oil, warm pide.", price: 18, photoUrl: P.bruschetta, tags: ["vegan", "vegetarian"] },
      { sectionId: "mezeler", name: "Haydari", description: "Strained yoghurt, garlic, mint, walnut.", price: 16, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "mezeler", name: "Sigara böreği (4pc)", description: "Crispy filo cigars filled with feta and parsley.", price: 22, photoUrl: P.dumplings, tags: ["vegetarian"] },
      { sectionId: "mezeler", name: "Dolma (5pc)", description: "Vine leaves stuffed with rice, pine nuts, currants.", price: 20, tags: ["vegan", "vegetarian"] },
      { sectionId: "kebaplar", name: "Adana kebap", description: "Hand-chopped lamb, red chilli, char-grilled on skewer.", price: 42, photoUrl: P.mici, tags: ["spicy", "popular"] },
      { sectionId: "kebaplar", name: "Urfa kebap", description: "Mild hand-chopped lamb, grilled over wood.", price: 40, photoUrl: P.mici },
      { sectionId: "kebaplar", name: "İskender", description: "Thin-sliced lamb doner over pide, tomato sauce, brown butter, yoghurt.", price: 48, photoUrl: P.steak, tags: ["popular", "chef-pick"] },
      { sectionId: "kebaplar", name: "Şiş kebap", description: "Marinated lamb cubes, tomato, pepper, onion.", price: 38 },
      { sectionId: "kebaplar", name: "Karışık ızgara", description: "Mixed grill for two — adana, urfa, şiş, chicken, lamb chop.", price: 98, photoUrl: P.mici, tags: ["chef-pick"] },
      { sectionId: "pideler", name: "Kaşarlı pide", description: "Boat-shaped flatbread, aged kaşar cheese.", price: 28, tags: ["vegetarian"] },
      { sectionId: "pideler", name: "Kıymalı pide", description: "Spiced minced lamb pide.", price: 32, photoUrl: P.pizza },
      { sectionId: "pideler", name: "Sucuklu pide", description: "Spicy Turkish beef sausage, kaşar.", price: 34, tags: ["spicy"] },
      { sectionId: "tatlilar", name: "Baklava (4pc)", description: "Handmade filo, pistachio, butter, honey syrup.", price: 22, photoUrl: P.pastry, tags: ["vegetarian", "popular"] },
      { sectionId: "tatlilar", name: "Künefe", description: "Kadayif pastry, stretchy cheese, pistachio, served hot.", price: 24, photoUrl: P.dessertPlated, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "tatlilar", name: "Sütlaç", description: "Clay-pot oven-baked rice pudding, cinnamon.", price: 16, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "icecekler", name: "Rakı (50ml)", description: "Aniseed spirit, on the rocks with water.", price: 24 },
      { sectionId: "icecekler", name: "Efes Pilsener", description: "Turkish lager, ice cold.", price: 14, photoUrl: P.beer },
      { sectionId: "icecekler", name: "Ayran", description: "Salted yoghurt drink, house-churned.", price: 10 },
      { sectionId: "icecekler", name: "Çay", description: "Turkish black tea in a tulip glass.", price: 6, photoUrl: P.tea, tags: ["popular"] },
      { sectionId: "icecekler", name: "Türk Kahvesi", description: "Stovetop-brewed, served with Turkish delight.", price: 12, photoUrl: P.espresso },
    ],
  ),

  "le-bistrot": makeMenu(
    "5",
    "French classical cooking without the spectacle. Foie gras, coq au vin, a cheese trolley that matters.",
    [
      { id: "entrees", name: "Entrées", intro: "To begin — simple, classical, French." },
      { id: "plats", name: "Plats Principaux", intro: "The heart of the meal. Honest plates, carefully cooked." },
      { id: "fromages", name: "Fromages", intro: "A pause before dessert. Ask about today's selection." },
      { id: "desserts", name: "Desserts", intro: "Sweet, classic, a little theatrical." },
      { id: "vins", name: "Vins & Digestifs", intro: drinksIntros.fr },
    ],
    [
      { sectionId: "entrees", name: "Foie gras mi-cuit", description: "House-terrine foie gras, fig chutney, brioche toast, Sauternes jelly.", price: 82, photoUrl: P.plated, tags: ["chef-pick"] },
      { sectionId: "entrees", name: "Escargots de Bourgogne", description: "Six wild Burgundy snails, garlic-parsley butter, crusty bread.", price: 68, photoUrl: P.fineDining },
      { sectionId: "entrees", name: "Soupe à l'oignon gratinée", description: "Slow-caramelised onion, beef consommé, Comté gratin.", price: 52, photoUrl: P.stew, tags: ["vegetarian"] },
      { sectionId: "entrees", name: "Tartare de bœuf", description: "Hand-cut Charolais beef, shallot, capers, Dijon, quail yolk.", price: 78 },
      { sectionId: "plats", name: "Steak au poivre", description: "Dry-aged ribeye, green peppercorn cognac sauce, pommes frites.", price: 165, photoUrl: P.steak, tags: ["chef-pick", "popular"] },
      { sectionId: "plats", name: "Coq au vin", description: "Free-range chicken braised in Burgundy, lardons, pearl onions, mushrooms.", price: 125, photoUrl: P.stew },
      { sectionId: "plats", name: "Canard à l'orange", description: "Roast Barbary duck breast, bitter-orange reduction, fondant potato.", price: 145, photoUrl: P.plated, tags: ["chef-pick"] },
      { sectionId: "plats", name: "Sole meunière", description: "Whole Dover sole, brown butter, lemon, capers, parsley.", price: 198, photoUrl: P.fineDining, tags: ["gluten-free"] },
      { sectionId: "plats", name: "Bœuf Wellington", description: "Beef fillet, mushroom duxelles, prosciutto, puff pastry (for two).", price: 285, tags: ["chef-pick"] },
      { sectionId: "fromages", name: "Plateau de fromages (5)", description: "Chef's selection of five artisanal French cheeses, walnut bread, quince.", price: 85, photoUrl: P.plated, tags: ["vegetarian"] },
      { sectionId: "fromages", name: "Camembert rôti", description: "Oven-roasted whole Camembert, honey, rosemary, toasted baguette.", price: 68, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Crème brûlée à la vanille", description: "Tahitian vanilla custard, torched sugar crust.", price: 58, photoUrl: P.dessertPlated, tags: ["popular", "vegetarian"] },
      { sectionId: "desserts", name: "Tarte Tatin", description: "Caramelised apple, flaky puff pastry, crème fraîche.", price: 62, photoUrl: P.pastry, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Soufflé au Grand Marnier", description: "Hot orange soufflé. 25 minutes. Order at the start of the meal.", price: 72, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "desserts", name: "Mille-feuille à la framboise", description: "Five layers of puff, vanilla cream, fresh raspberries.", price: 58, tags: ["vegetarian"] },
      { sectionId: "vins", name: "Champagne Brut (flute)", description: "Perrier-Jouët Grand Brut.", price: 85, photoUrl: P.wineGlass },
      { sectionId: "vins", name: "Saint-Émilion Grand Cru (glass)", description: "5-year Bordeaux, structured, long.", price: 75, photoUrl: P.wineRed },
      { sectionId: "vins", name: "Chablis 1er Cru (glass)", description: "Mineral Burgundy white.", price: 68 },
      { sectionId: "vins", name: "Pastis Ricard", description: "Provençal anise aperitif, water on the side.", price: 28 },
      { sectionId: "vins", name: "Kir Royal", description: "Crème de cassis, Champagne.", price: 48, photoUrl: P.cocktail },
      { sectionId: "vins", name: "Armagnac 10 ans", description: "After-dinner, neat.", price: 58 },
    ],
  ),

  "brasserie-moderne": makeMenu(
    "12",
    "Brasserie classics, a modern wine list, oysters most nights.",
    [
      { id: "entrees", name: "Entrées", intro: "Brasserie staples, made properly." },
      { id: "plats", name: "Plats", intro: "Aged beef, wild fish, careful sauces." },
      { id: "desserts", name: "Desserts", intro: "Classical French, with some theatre." },
      { id: "vins", name: "Vins & Apéritifs", intro: drinksIntros.fr },
    ],
    [
      { sectionId: "entrees", name: "Huîtres fines de claire (6)", description: "Six Marennes-Oléron oysters, shallot vinaigrette, lemon.", price: 95, photoUrl: P.fineDining, tags: ["gluten-free"] },
      { sectionId: "entrees", name: "Salade Lyonnaise", description: "Frisée, lardons, poached egg, Dijon vinaigrette.", price: 62 },
      { sectionId: "entrees", name: "Velouté de champignons", description: "Porcini velouté, truffle oil, chive.", price: 68, photoUrl: P.stew, tags: ["vegetarian"] },
      { sectionId: "entrees", name: "Rillettes de canard", description: "House duck rillettes, cornichons, grilled sourdough.", price: 72, photoUrl: P.plated },
      { sectionId: "plats", name: "Entrecôte bordelaise", description: "Aged entrecôte, bordelaise jus, bone marrow, frites.", price: 185, photoUrl: P.steak, tags: ["chef-pick", "popular"] },
      { sectionId: "plats", name: "Magret de canard", description: "Seared duck breast, pickled cherry, salsify.", price: 165, photoUrl: P.plated, tags: ["chef-pick"] },
      { sectionId: "plats", name: "Bouillabaisse marseillaise", description: "Mediterranean fish stew, rouille, croutons.", price: 195, photoUrl: P.stew },
      { sectionId: "plats", name: "Filet de bar", description: "Wild sea bass, fennel, bisque, saffron potato.", price: 175, photoUrl: P.fineDining, tags: ["gluten-free"] },
      { sectionId: "desserts", name: "Mille-feuille classique", description: "Vanilla mille-feuille, caramel sauce.", price: 65, photoUrl: P.dessertPlated, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Île flottante", description: "Poached meringue, crème anglaise, praline.", price: 55, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Plateau de fromages", description: "Six regional cheeses, fig confit, walnut bread.", price: 75, tags: ["vegetarian"] },
      { sectionId: "vins", name: "Sancerre (glass)", description: "Crisp Loire white, citrus and flint.", price: 58, photoUrl: P.wineGlass },
      { sectionId: "vins", name: "Châteauneuf-du-Pape (glass)", description: "Southern Rhône red, generous and warm.", price: 78, photoUrl: P.wineRed },
      { sectionId: "vins", name: "Kir classique", description: "Blackcurrant liqueur, Aligoté.", price: 36 },
      { sectionId: "vins", name: "Calvados hors d'âge", description: "To finish.", price: 52 },
    ],
  ),

  "dim-sum-house": makeMenu(
    "6",
    "Small baskets, steamed and fried. The Cantonese way to eat lunch — all day.",
    [
      { id: "dimsum", name: "Dim Sum", intro: "Small baskets, steamed and fried — the Cantonese way to eat lunch." },
      { id: "mains", name: "Mains", intro: "Family-style. Order for the table." },
      { id: "noodlesrice", name: "Noodles & Rice", intro: "The wok is loud for a reason." },
      { id: "desserts", name: "Desserts", intro: "Light, not too sweet." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.cn },
    ],
    [
      { sectionId: "dimsum", name: "Har gow (4pc)", description: "Translucent shrimp dumplings.", price: 32, photoUrl: P.dumplings, tags: ["popular"] },
      { sectionId: "dimsum", name: "Siu mai (4pc)", description: "Open-topped pork & shrimp dumplings.", price: 30, photoUrl: P.dumplings, tags: ["popular"] },
      { sectionId: "dimsum", name: "Char siu bao (3pc)", description: "Fluffy steamed buns, sweet BBQ pork.", price: 28, photoUrl: P.asian },
      { sectionId: "dimsum", name: "Xiao long bao (6pc)", description: "Shanghai soup dumplings, black vinegar ginger.", price: 42, photoUrl: P.asian, tags: ["chef-pick"] },
      { sectionId: "dimsum", name: "Cheung fun with shrimp", description: "Silky rice rolls, sweet soy.", price: 34 },
      { sectionId: "dimsum", name: "Crystal prawn dumpling", description: "Translucent dumpling, whole prawn, chive.", price: 36, tags: ["gluten-free"] },
      { sectionId: "mains", name: "Peking duck (half)", description: "Crisp-skin duck, pancakes, cucumber, spring onion, hoisin.", price: 145, photoUrl: P.plated, tags: ["chef-pick", "popular"] },
      { sectionId: "mains", name: "Kung pao chicken", description: "Diced chicken, peanuts, dried chilli, Sichuan peppercorn.", price: 58, photoUrl: P.wok, tags: ["spicy"] },
      { sectionId: "mains", name: "Mapo tofu", description: "Soft tofu, Sichuan chilli bean paste, minced pork.", price: 46, tags: ["spicy"] },
      { sectionId: "mains", name: "Salt & pepper squid", description: "Crispy squid, chilli, garlic, spring onion.", price: 52, photoUrl: P.wok },
      { sectionId: "noodlesrice", name: "Beef chow fun", description: "Wide rice noodles, seared beef, Chinese chive, bean sprout.", price: 48, photoUrl: P.wok },
      { sectionId: "noodlesrice", name: "Singapore noodles", description: "Curried rice vermicelli, shrimp, char siu, egg.", price: 46, tags: ["spicy"] },
      { sectionId: "noodlesrice", name: "Fried rice with shrimp", description: "Wok-fired rice, egg, peas, spring onion.", price: 42 },
      { sectionId: "desserts", name: "Mango pudding", description: "Alphonso mango custard, coconut cream.", price: 22, photoUrl: P.dessertPlated, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "desserts", name: "Sesame balls (3pc)", description: "Fried glutinous rice, sweet red bean.", price: 18, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Jasmine tea (pot)", description: "Endless refills.", price: 16, photoUrl: P.tea, tags: ["popular"] },
      { sectionId: "drinks", name: "Tsingtao", description: "Chinese pilsner.", price: 18, photoUrl: P.beer },
      { sectionId: "drinks", name: "Shaoxing rice wine (carafe)", description: "Warmed, traditional.", price: 42 },
      { sectionId: "drinks", name: "Lychee cocktail", description: "Vodka, lychee, lime.", price: 34, photoUrl: P.cocktail },
    ],
  ),

  "golden-dragon": makeMenu(
    "17",
    "Cantonese banquet cooking — whole duck, live seafood, a proper Peking duck service.",
    [
      { id: "starters", name: "Starters", intro: "Openers for the table. Go heavy on soup." },
      { id: "peking", name: "Peking Duck", intro: "Our signature. Pre-order suggested for the whole three-course service." },
      { id: "mains", name: "Mains", intro: "Banquet-style, meant to share." },
      { id: "rice", name: "Rice & Noodles", intro: "Ordered last, eaten first." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.cn },
    ],
    [
      { sectionId: "starters", name: "Crispy aromatic duck (half)", description: "Crisp-skin duck, pancakes, cucumber, spring onion, hoisin.", price: 125, photoUrl: P.asian, tags: ["chef-pick"] },
      { sectionId: "starters", name: "Salt & pepper soft-shell crab", description: "Whole soft-shell crab, chilli, garlic, spring onion.", price: 95, photoUrl: P.wok, tags: ["spicy"] },
      { sectionId: "starters", name: "Prawn toast", description: "Whole prawns on sesame-crusted toast.", price: 48 },
      { sectionId: "starters", name: "Hot & sour soup", description: "Bamboo, wood ear, tofu, black vinegar, white pepper.", price: 42, photoUrl: P.stew, tags: ["spicy"] },
      { sectionId: "peking", name: "Whole Peking duck (3 courses)", description: "Whole duck carved tableside — pancakes, stir-fried lettuce wraps, and broth to finish. Pre-order recommended.", price: 385, photoUrl: P.plated, tags: ["chef-pick", "popular"] },
      { sectionId: "peking", name: "Peking duck (half)", description: "Half duck, pancakes, trimmings.", price: 195, photoUrl: P.plated, tags: ["popular"] },
      { sectionId: "mains", name: "Whole steamed sea bass", description: "Ginger, spring onion, soy. Market weight.", price: 225, photoUrl: P.fineDining, tags: ["gluten-free"] },
      { sectionId: "mains", name: "Mongolian lamb", description: "Wok-seared lamb, spring onion, ginger, hoisin.", price: 145, photoUrl: P.wok },
      { sectionId: "mains", name: "Szechuan beef", description: "Beef slices in Szechuan chilli oil, numbing peppercorn.", price: 128, tags: ["spicy"] },
      { sectionId: "mains", name: "Buddha's delight", description: "Seasonal Chinese vegetables, tofu, black mushroom.", price: 85, tags: ["vegetarian", "vegan"] },
      { sectionId: "rice", name: "Yangzhou fried rice", description: "Classic fried rice with char siu, shrimp, egg, peas.", price: 68 },
      { sectionId: "rice", name: "Dan dan noodles", description: "Sichuan noodles, sesame paste, chilli oil, minced pork.", price: 72, tags: ["spicy"] },
      { sectionId: "drinks", name: "Shaoxing rice wine", description: "Warmed, from a carafe.", price: 55, photoUrl: P.wineGlass },
      { sectionId: "drinks", name: "Tsingtao draft", description: "Chinese pilsner.", price: 22, photoUrl: P.beer },
      { sectionId: "drinks", name: "Jasmine tea pot", description: "Refills on the house.", price: 18, photoUrl: P.tea, tags: ["popular"] },
      { sectionId: "drinks", name: "Plum wine", description: "Japanese umeshu, on the rocks.", price: 28 },
    ],
  ),

  "el-toro-tapas": makeMenu(
    "7",
    "Small plates, big wine list, paella on weekends. Spain in Floreasca.",
    [
      { id: "tapas", name: "Tapas", intro: "Small plates for the table. Order many." },
      { id: "raciones", name: "Raciones", intro: "Larger portions. Share or don't." },
      { id: "paella", name: "Paellas", intro: "One pan, 30 minutes. From the heart of Valencia." },
      { id: "postres", name: "Postres", intro: "A sweet finish — crema catalana is the answer." },
      { id: "bebidas", name: "Bebidas", intro: drinksIntros.es },
    ],
    [
      { sectionId: "tapas", name: "Patatas bravas", description: "Crisp potatoes, spicy bravas, aioli.", price: 24, photoUrl: P.plated, tags: ["vegetarian", "spicy", "popular"] },
      { sectionId: "tapas", name: "Jamón ibérico de bellota", description: "Acorn-fed 36-month Iberian ham, pan con tomate.", price: 58, photoUrl: P.plated, tags: ["gluten-free", "chef-pick"] },
      { sectionId: "tapas", name: "Tortilla española", description: "Classic Spanish potato omelette, aioli.", price: 28, photoUrl: P.bruschetta, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "tapas", name: "Croquetas de jamón (4)", description: "Crispy ham croquettes, béchamel.", price: 26, photoUrl: P.dumplings },
      { sectionId: "tapas", name: "Gambas al ajillo", description: "Sizzling prawns, garlic, chilli, olive oil.", price: 42, photoUrl: P.wok, tags: ["spicy", "gluten-free"] },
      { sectionId: "tapas", name: "Pulpo a la gallega", description: "Galician octopus, pimentón, olive oil, sea salt.", price: 54, photoUrl: P.fineDining, tags: ["gluten-free", "chef-pick"] },
      { sectionId: "raciones", name: "Chorizo al vino tinto", description: "Chorizo simmered in red wine.", price: 38 },
      { sectionId: "raciones", name: "Queso manchego (12-month)", description: "Aged Manchego, membrillo, Marcona almonds.", price: 44, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "raciones", name: "Pimientos de Padrón", description: "Blistered Padrón peppers, Maldon salt.", price: 32, tags: ["vegan", "vegetarian", "gluten-free"] },
      { sectionId: "paella", name: "Paella valenciana (2 personas)", description: "Rabbit, chicken, green beans, artichoke, bomba rice.", price: 168, photoUrl: P.wok, tags: ["popular"] },
      { sectionId: "paella", name: "Paella de mariscos (2 personas)", description: "Prawns, mussels, clams, squid, saffron.", price: 198, photoUrl: P.wok, tags: ["chef-pick", "popular", "gluten-free"] },
      { sectionId: "paella", name: "Arroz negro (2 personas)", description: "Squid-ink rice, calamari, aioli.", price: 175, tags: ["gluten-free"] },
      { sectionId: "postres", name: "Crema catalana", description: "Lemon-scented custard, torched sugar.", price: 24, photoUrl: P.dessertPlated, tags: ["vegetarian"] },
      { sectionId: "postres", name: "Churros con chocolate", description: "Warm churros, dark chocolate dip.", price: 22, photoUrl: P.pastry, tags: ["vegetarian", "popular"] },
      { sectionId: "postres", name: "Tarta de Santiago", description: "Almond cake, powdered sugar, St. James cross.", price: 20, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "bebidas", name: "Rioja Reserva (glass)", description: "Tempranillo, 5-year, cherry and leather.", price: 48, photoUrl: P.wineRed },
      { sectionId: "bebidas", name: "Albariño (glass)", description: "Galician white, bright and saline.", price: 42 },
      { sectionId: "bebidas", name: "Sangría roja (jug)", description: "Red wine, orange, brandy, cinnamon.", price: 95, photoUrl: P.cocktail, tags: ["popular"] },
      { sectionId: "bebidas", name: "Cava Brut (flute)", description: "Spanish sparkling, crisp.", price: 38, photoUrl: P.wineGlass },
      { sectionId: "bebidas", name: "Estrella Galicia", description: "Spanish lager.", price: 16, photoUrl: P.beer },
    ],
  ),

  "maharaja-palace": makeMenu(
    "8",
    "Old Delhi tandoor, Hyderabadi biryani, the family butter chicken recipe.",
    [
      { id: "starters", name: "Starters", intro: "Small bites, big flavours." },
      { id: "tandoor", name: "From the Tandoor", intro: "The clay oven is ancient. The char is real." },
      { id: "curries", name: "Curries", intro: "Slow-cooked, layered, unhurried." },
      { id: "biryani", name: "Biryani & Rice", intro: "Saffron, time, patience." },
      { id: "breads", name: "Breads", intro: "Straight from the tandoor, always." },
      { id: "desserts", name: "Desserts", intro: "Cardamom, rose, milk — the Indian trinity." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.in },
    ],
    [
      { sectionId: "starters", name: "Samosas (2pc)", description: "Spiced potato & pea, tamarind chutney.", price: 22, photoUrl: P.dumplings, tags: ["vegetarian", "vegan"] },
      { sectionId: "starters", name: "Onion bhaji (6pc)", description: "Crispy onion fritters, mint yoghurt.", price: 20, tags: ["vegetarian"] },
      { sectionId: "starters", name: "Chicken 65", description: "Spicy South Indian fried chicken, curry leaf.", price: 32, photoUrl: P.wok, tags: ["spicy"] },
      { sectionId: "starters", name: "Paneer tikka", description: "Tandoor-grilled paneer, bell pepper, mint chutney.", price: 34, photoUrl: P.plated, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "tandoor", name: "Chicken tikka", description: "Marinated chicken grilled in the tandoor.", price: 48, photoUrl: P.steak, tags: ["popular", "gluten-free"] },
      { sectionId: "tandoor", name: "Lamb seekh kebab", description: "Minced lamb kebab, mint chutney.", price: 52, photoUrl: P.mici },
      { sectionId: "tandoor", name: "Tandoori mixed grill", description: "Chicken tikka, seekh, lamb chop, paneer.", price: 82, photoUrl: P.mici, tags: ["chef-pick"] },
      { sectionId: "curries", name: "Butter chicken", description: "Tandoori chicken, creamy tomato-cashew sauce, fenugreek.", price: 58, photoUrl: P.stew, tags: ["popular", "chef-pick"] },
      { sectionId: "curries", name: "Chicken tikka masala", description: "Grilled chicken, tomato & cream masala.", price: 56, photoUrl: P.stew, tags: ["popular"] },
      { sectionId: "curries", name: "Lamb rogan josh", description: "Kashmiri braised lamb, deep chilli colour, fennel & ginger.", price: 68, tags: ["spicy"] },
      { sectionId: "curries", name: "Palak paneer", description: "Spinach & paneer in cumin-tempered sauce.", price: 48, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "curries", name: "Chana masala", description: "Chickpeas, tomato, ginger, garam masala.", price: 42, tags: ["vegan", "vegetarian"] },
      { sectionId: "curries", name: "Vindaloo (lamb)", description: "Goan chilli-vinegar lamb curry. Hot.", price: 62, tags: ["spicy"] },
      { sectionId: "biryani", name: "Chicken biryani", description: "Fragrant basmati, saffron, chicken, fried onion, raita.", price: 58, photoUrl: P.asian, tags: ["chef-pick"] },
      { sectionId: "biryani", name: "Lamb biryani", description: "Hyderabadi-style slow-cooked dum biryani.", price: 72, photoUrl: P.asian },
      { sectionId: "biryani", name: "Vegetable biryani", description: "Mixed vegetable basmati, whole spices, raita.", price: 48, tags: ["vegetarian"] },
      { sectionId: "breads", name: "Naan", description: "Traditional clay-oven flatbread.", price: 12, tags: ["vegetarian"] },
      { sectionId: "breads", name: "Garlic naan", description: "Naan brushed with garlic butter and coriander.", price: 14, tags: ["vegetarian", "popular"] },
      { sectionId: "breads", name: "Peshwari naan", description: "Stuffed with coconut, raisin, pistachio.", price: 18, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Gulab jamun (3pc)", description: "Milk dumplings in cardamom rose syrup.", price: 18, photoUrl: P.pastry, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Kheer", description: "Basmati rice pudding, cardamom, pistachio.", price: 16, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "drinks", name: "Mango lassi", description: "Yoghurt, mango, cardamom.", price: 22, photoUrl: P.cocktail, tags: ["popular"] },
      { sectionId: "drinks", name: "Masala chai", description: "Cardamom, cinnamon, ginger, black tea.", price: 18, photoUrl: P.tea },
      { sectionId: "drinks", name: "Kingfisher Premium", description: "Indian lager, cold.", price: 18, photoUrl: P.beer },
      { sectionId: "drinks", name: "Salted lassi", description: "Traditional salted yoghurt drink.", price: 18 },
    ],
  ),

  "garden-grill": makeMenu(
    "9",
    "Beef ground daily, ribs smoked 12 hours, bourbon list worth reading.",
    [
      { id: "starters", name: "Starters", intro: "To start. Share the wings." },
      { id: "burgers", name: "Burgers", intro: "Beef ground daily. No shortcuts." },
      { id: "mains", name: "Mains", intro: "Serious plates — bring an appetite." },
      { id: "sides", name: "Sides", intro: "Because a burger alone isn't a meal." },
      { id: "desserts", name: "Desserts", intro: "Big, sweet, proud." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.us },
    ],
    [
      { sectionId: "starters", name: "Buffalo wings (8pc)", description: "House-brined wings, blue cheese, celery.", price: 36, photoUrl: P.mici, tags: ["spicy", "popular"] },
      { sectionId: "starters", name: "Loaded nachos", description: "Cheddar, pulled pork, jalapeño, sour cream, guacamole.", price: 42, photoUrl: P.plated, tags: ["spicy"] },
      { sectionId: "starters", name: "Caesar salad", description: "Romaine, anchovy dressing, parmesan, sourdough croutons.", price: 38 },
      { sectionId: "starters", name: "Mac & cheese bites", description: "Fried mac & cheese balls, ranch dip.", price: 28, tags: ["vegetarian"] },
      { sectionId: "burgers", name: "Classic cheeseburger", description: "180g beef, aged cheddar, lettuce, tomato, pickle, burger sauce.", price: 48, photoUrl: P.steak, tags: ["popular"] },
      { sectionId: "burgers", name: "BBQ bacon burger", description: "Smoked bacon, BBQ sauce, onion ring, sharp cheddar.", price: 54, photoUrl: P.steak, tags: ["chef-pick", "popular"] },
      { sectionId: "burgers", name: "Double smash", description: "Two smash patties, American cheese, special sauce.", price: 58 },
      { sectionId: "burgers", name: "Mushroom Swiss burger", description: "Sautéed mushrooms, Swiss cheese, garlic aioli.", price: 52 },
      { sectionId: "burgers", name: "Black-bean burger", description: "Smoky black-bean patty, chipotle mayo.", price: 42, tags: ["vegetarian", "vegan"] },
      { sectionId: "mains", name: "Baby back ribs (half rack)", description: "12-hour smoked ribs, BBQ glaze, slaw.", price: 78, photoUrl: P.mici, tags: ["popular", "chef-pick"] },
      { sectionId: "mains", name: "Buttermilk fried chicken", description: "Crisp fried chicken thigh, honey butter, pickled jalapeño.", price: 58, photoUrl: P.wok },
      { sectionId: "mains", name: "NY strip steak", description: "300g dry-aged NY strip, herb butter, fries.", price: 125, photoUrl: P.steak },
      { sectionId: "sides", name: "Hand-cut fries", description: "Maldon salt, rosemary.", price: 18, tags: ["vegetarian", "vegan"] },
      { sectionId: "sides", name: "Truffle fries", description: "Parmesan, truffle oil, chive.", price: 28, tags: ["vegetarian"] },
      { sectionId: "sides", name: "Coleslaw", description: "Classic buttermilk slaw.", price: 14, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "NY cheesecake", description: "Classic cheesecake, berry compote.", price: 28, photoUrl: P.dessertPlated, tags: ["vegetarian", "popular"] },
      { sectionId: "desserts", name: "Apple pie à la mode", description: "Warm apple pie, vanilla ice cream.", price: 26, photoUrl: P.pastry, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Craft IPA", description: "Local brewery, citrus-hopped.", price: 26, photoUrl: P.beer },
      { sectionId: "drinks", name: "Bourbon old-fashioned", description: "Woodford Reserve, bitters, sugar, orange peel.", price: 42, photoUrl: P.cocktail, tags: ["popular"] },
      { sectionId: "drinks", name: "Moscow mule", description: "Vodka, ginger beer, lime, copper mug.", price: 36, photoUrl: P.cocktail },
      { sectionId: "drinks", name: "Chocolate milkshake", description: "Thick, proper, two straws optional.", price: 28 },
      { sectionId: "drinks", name: "Coke / Sprite / Fanta", description: "The classics.", price: 12 },
    ],
  ),

  "mezze-bar": makeMenu(
    "10",
    "Cold mezze, hot mezze, charcoal grill, Lebanese wine from Château Musar.",
    [
      { id: "cold", name: "Cold Mezze", intro: "Cold small dishes — the table always starts here." },
      { id: "hot", name: "Hot Mezze", intro: "From the fryer, the oven, the grill." },
      { id: "grills", name: "Grills & Mains", intro: "Charcoal meets marinade." },
      { id: "desserts", name: "Desserts", intro: "Syrup, nuts, pastry — three things done right." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.lb },
    ],
    [
      { sectionId: "cold", name: "Hummus", description: "Silky chickpea purée, tahini, cumin-lemon oil, warm pita.", price: 24, photoUrl: P.bruschetta, tags: ["vegan", "vegetarian", "popular"] },
      { sectionId: "cold", name: "Baba ghanoush", description: "Charred aubergine, tahini, pomegranate, mint.", price: 24, photoUrl: P.bruschetta, tags: ["vegan", "vegetarian"] },
      { sectionId: "cold", name: "Tabbouleh", description: "Parsley, tomato, bulgur, lemon, olive oil.", price: 22, tags: ["vegetarian", "vegan"] },
      { sectionId: "cold", name: "Fattoush", description: "Mixed greens, crispy pita, sumac, pomegranate molasses.", price: 26, tags: ["vegetarian", "vegan"] },
      { sectionId: "cold", name: "Muhammara", description: "Walnut, roasted red pepper, pomegranate molasses.", price: 26, tags: ["vegan", "vegetarian"] },
      { sectionId: "cold", name: "Labneh", description: "Strained yoghurt, za'atar, olive oil.", price: 22, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "hot", name: "Falafel (6pc)", description: "Crispy chickpea-herb patties, tahini.", price: 28, photoUrl: P.dumplings, tags: ["vegan", "vegetarian"] },
      { sectionId: "hot", name: "Kibbeh (4pc)", description: "Bulgur shells stuffed with spiced lamb and pine nuts.", price: 32 },
      { sectionId: "hot", name: "Sambousek", description: "Fried pastries with lamb or cheese.", price: 28 },
      { sectionId: "hot", name: "Arayes", description: "Grilled pita stuffed with spiced lamb.", price: 34, photoUrl: P.pizza, tags: ["spicy"] },
      { sectionId: "grills", name: "Shish taouk", description: "Marinated chicken skewers, garlic toum.", price: 48, photoUrl: P.mici, tags: ["popular"] },
      { sectionId: "grills", name: "Kafta kebab", description: "Spiced lamb kofta, grilled onion, tomato, pita.", price: 52, photoUrl: P.mici, tags: ["chef-pick"] },
      { sectionId: "grills", name: "Lamb shawarma", description: "Slow-turned shawarma, garlic sauce, pickles.", price: 54, photoUrl: P.steak, tags: ["popular"] },
      { sectionId: "grills", name: "Mixed grill platter", description: "Shish taouk, kafta, shish kebab, rice, bread.", price: 95, photoUrl: P.mici, tags: ["chef-pick"] },
      { sectionId: "desserts", name: "Baklava (4pc)", description: "Handmade filo, pistachio, honey.", price: 24, photoUrl: P.pastry, tags: ["vegetarian", "popular"] },
      { sectionId: "desserts", name: "Knafeh", description: "Crisp kadayif, stretchy cheese, pistachio, rose syrup.", price: 28, photoUrl: P.dessertPlated, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "desserts", name: "Ashta with honey", description: "Clotted cream, honey, pistachio.", price: 22, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Château Musar (glass)", description: "Famous Lebanese red — cedar, fig, leather.", price: 68, photoUrl: P.wineRed, tags: ["chef-pick"] },
      { sectionId: "drinks", name: "Arak (50ml)", description: "Aniseed Levantine spirit, with water and ice.", price: 26 },
      { sectionId: "drinks", name: "Almaza", description: "Lebanese pilsner.", price: 18, photoUrl: P.beer },
      { sectionId: "drinks", name: "Fresh mint lemonade", description: "Lemon, mint, just-enough sugar.", price: 18, tags: ["popular"] },
      { sectionId: "drinks", name: "Pomegranate juice", description: "Fresh-pressed.", price: 22 },
    ],
  ),

  "wok-express": makeMenu(
    "13",
    "Bangkok street food, Bucharest prices. Loud wok, quick service.",
    [
      { id: "starters", name: "Starters", intro: "Sharp, bright, spicy — the Thai way to begin." },
      { id: "curries", name: "Curries", intro: "Coconut, aromatics, chilli. Order rice." },
      { id: "noodles", name: "Noodles & Rice", intro: "Quick, loud, essential." },
      { id: "desserts", name: "Desserts", intro: "Mango season is always." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.th },
    ],
    [
      { sectionId: "starters", name: "Tom yum gai", description: "Hot & sour chicken soup, lemongrass, kaffir lime, chilli.", price: 24, photoUrl: P.stew, tags: ["spicy", "popular"] },
      { sectionId: "starters", name: "Tom kha gai", description: "Coconut chicken soup, galangal, lime.", price: 24, tags: ["gluten-free"] },
      { sectionId: "starters", name: "Chicken satay (4pc)", description: "Grilled chicken skewers, peanut sauce, cucumber relish.", price: 26, photoUrl: P.mici },
      { sectionId: "starters", name: "Vegetable spring rolls (4pc)", description: "Crispy spring rolls, sweet chilli sauce.", price: 22, photoUrl: P.dumplings, tags: ["vegan", "vegetarian"] },
      { sectionId: "starters", name: "Som tam (papaya salad)", description: "Green papaya, peanut, lime, chilli, dried shrimp.", price: 24, tags: ["spicy", "gluten-free"] },
      { sectionId: "curries", name: "Green curry chicken", description: "Thai green curry paste, coconut milk, Thai basil, aubergine.", price: 36, photoUrl: P.stew, tags: ["spicy", "popular"] },
      { sectionId: "curries", name: "Red curry beef", description: "Red curry, coconut milk, bamboo shoots, sweet basil.", price: 38, photoUrl: P.stew, tags: ["spicy"] },
      { sectionId: "curries", name: "Massaman curry lamb", description: "Mild aromatic curry, potato, peanut, tamarind.", price: 42, photoUrl: P.wok, tags: ["chef-pick", "gluten-free"] },
      { sectionId: "curries", name: "Panang curry prawn", description: "Thick red curry, kaffir lime, Thai basil.", price: 44, tags: ["spicy"] },
      { sectionId: "noodles", name: "Pad Thai", description: "Rice noodles, tamarind, egg, beansprout, peanut, lime.", price: 34, photoUrl: P.wok, tags: ["popular"] },
      { sectionId: "noodles", name: "Pad See Ew", description: "Wide rice noodles, dark soy, Chinese broccoli, egg.", price: 34, photoUrl: P.wok },
      { sectionId: "noodles", name: "Drunken noodles (pad kee mao)", description: "Wide noodles, basil, chilli, fish sauce.", price: 36, tags: ["spicy"] },
      { sectionId: "noodles", name: "Pineapple fried rice", description: "Fried rice with pineapple, cashew, raisin, curry powder.", price: 32, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Mango sticky rice", description: "Alphonso mango, coconut sticky rice, sesame.", price: 24, photoUrl: P.dessertPlated, tags: ["vegetarian", "gluten-free", "popular"] },
      { sectionId: "desserts", name: "Fried banana", description: "Crispy fried banana, coconut ice cream.", price: 18, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Thai iced tea", description: "Black tea, condensed milk, signature orange.", price: 18, photoUrl: P.tea, tags: ["popular"] },
      { sectionId: "drinks", name: "Singha", description: "Thai lager, cold.", price: 18, photoUrl: P.beer },
      { sectionId: "drinks", name: "Chang", description: "Thai lager, cold.", price: 18 },
      { sectionId: "drinks", name: "Coconut water", description: "Fresh, from the shell.", price: 16 },
    ],
  ),

  "taverna-greceasca": makeMenu(
    "14",
    "Fire, lemon, oregano — the trinity. Fish straight from the Aegean.",
    [
      { id: "mezedes", name: "Mezedes", intro: "Small dishes to share, the way Greeks start every meal." },
      { id: "salates", name: "Salates", intro: "Tomato, feta, time." },
      { id: "grills", name: "From the Grill", intro: "Fire, lemon, oregano. That's the trinity." },
      { id: "desserts", name: "Desserts", intro: "Honey, walnut, phyllo — mostly honey." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.gr },
    ],
    [
      { sectionId: "mezedes", name: "Tzatziki", description: "Strained yoghurt, cucumber, garlic, dill, pita.", price: 22, photoUrl: P.bruschetta, tags: ["vegetarian", "popular"] },
      { sectionId: "mezedes", name: "Melitzanosalata", description: "Smoky aubergine, walnut, olive oil.", price: 24, tags: ["vegan", "vegetarian"] },
      { sectionId: "mezedes", name: "Taramasalata", description: "Whipped cod-roe spread, lemon, pita.", price: 26, tags: ["gluten-free"] },
      { sectionId: "mezedes", name: "Saganaki", description: "Pan-seared graviera cheese, lemon, oregano.", price: 32, photoUrl: P.plated, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "mezedes", name: "Dolmadakia (6pc)", description: "Vine leaves stuffed with rice, herbs, lemon.", price: 26, tags: ["vegan", "vegetarian"] },
      { sectionId: "salates", name: "Horiatiki (Greek salad)", description: "Tomato, cucumber, red onion, olives, feta, oregano.", price: 32, photoUrl: P.bruschetta, tags: ["vegetarian", "gluten-free", "popular"] },
      { sectionId: "salates", name: "Politiki salata", description: "Cabbage, carrot, pepper, parsley, vinaigrette.", price: 24, tags: ["vegan", "vegetarian"] },
      { sectionId: "grills", name: "Souvlaki chicken", description: "Grilled marinated chicken skewers, pita, tzatziki, chips.", price: 42, photoUrl: P.mici, tags: ["popular"] },
      { sectionId: "grills", name: "Souvlaki pork", description: "Marinated pork skewers, pita, tzatziki, chips.", price: 42, photoUrl: P.mici },
      { sectionId: "grills", name: "Moussaka", description: "Layered aubergine, spiced lamb, béchamel.", price: 48, photoUrl: P.stew, tags: ["popular"] },
      { sectionId: "grills", name: "Grilled whole sea bream", description: "Whole bream, lemon, oregano, olive oil.", price: 78, photoUrl: P.fineDining, tags: ["chef-pick", "gluten-free"] },
      { sectionId: "grills", name: "Grilled octopus", description: "Char-grilled octopus, lemon, olive oil, capers.", price: 72, photoUrl: P.fineDining, tags: ["chef-pick", "gluten-free"] },
      { sectionId: "desserts", name: "Baklava", description: "Filo, walnut, pistachio, thyme honey.", price: 22, photoUrl: P.pastry, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Galaktoboureko", description: "Semolina custard, crisp filo, syrup.", price: 22, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Loukoumades", description: "Honey doughnuts, cinnamon, walnut.", price: 20, photoUrl: P.dessertPlated, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Assyrtiko (glass)", description: "Crisp Santorini white — citrus and sea salt.", price: 42, photoUrl: P.wineGlass },
      { sectionId: "drinks", name: "Ouzo (50ml)", description: "Aniseed spirit, with ice.", price: 18 },
      { sectionId: "drinks", name: "Mythos", description: "Greek lager.", price: 16, photoUrl: P.beer },
      { sectionId: "drinks", name: "Greek coffee", description: "Strong, unfiltered, slow-sipped.", price: 14, photoUrl: P.espresso },
      { sectionId: "drinks", name: "Metaxa 7 Star", description: "Greek brandy to finish.", price: 32 },
    ],
  ),

  "seoul-kitchen": makeMenu(
    "15",
    "Grilled at the table, shared at the table, washed down with soju.",
    [
      { id: "banchan", name: "Banchan & Starters", intro: "Small side dishes that never stop arriving." },
      { id: "bbq", name: "Korean BBQ", intro: "Grilled at your table. The smoke is the feature." },
      { id: "mains", name: "Stews & Rice", intro: "Hot pot, bibimbap, comfort." },
      { id: "desserts", name: "Desserts", intro: "Light, icy, sweet." },
      { id: "drinks", name: "Drinks", intro: drinksIntros.ko },
    ],
    [
      { sectionId: "banchan", name: "Banchan platter", description: "Chef's selection of five small sides — kimchi, pickled radish, seasoned spinach, bean sprout, marinated tofu.", price: 32, photoUrl: P.plated, tags: ["vegetarian", "chef-pick"] },
      { sectionId: "banchan", name: "Kimchi jeon", description: "Kimchi pancake, soy-vinegar dip.", price: 28, photoUrl: P.pizza, tags: ["spicy", "vegetarian"] },
      { sectionId: "banchan", name: "Mandu (6pc)", description: "Pan-fried dumplings, soy-sesame dip.", price: 32, photoUrl: P.dumplings },
      { sectionId: "banchan", name: "Tteokbokki", description: "Chewy rice cakes in sweet-spicy gochujang sauce.", price: 34, photoUrl: P.wok, tags: ["spicy", "vegetarian", "popular"] },
      { sectionId: "bbq", name: "Bulgogi", description: "Marinated thin-sliced ribeye, sesame, onion, grilled at the table.", price: 82, photoUrl: P.steak, tags: ["popular", "chef-pick"] },
      { sectionId: "bbq", name: "Galbi (short ribs)", description: "Sweet-soy marinated beef short ribs, sesame.", price: 95, photoUrl: P.steak, tags: ["chef-pick"] },
      { sectionId: "bbq", name: "Samgyeopsal", description: "Pork belly, lettuce wrap, ssamjang, garlic.", price: 72, photoUrl: P.mici },
      { sectionId: "bbq", name: "Dak galbi", description: "Spicy gochujang chicken, cabbage, sweet potato, rice cake.", price: 62, photoUrl: P.wok, tags: ["spicy", "popular"] },
      { sectionId: "mains", name: "Dolsot bibimbap", description: "Sizzling stone bowl, rice, vegetables, beef, egg, gochujang.", price: 48, photoUrl: P.asian, tags: ["popular"] },
      { sectionId: "mains", name: "Bibimbap (classic)", description: "Mixed rice bowl, vegetables, beef, egg.", price: 42 },
      { sectionId: "mains", name: "Kimchi jjigae", description: "Aged kimchi stew, pork belly, tofu.", price: 46, photoUrl: P.stew, tags: ["spicy"] },
      { sectionId: "mains", name: "Japchae", description: "Sweet potato glass noodles, vegetables, beef, sesame.", price: 42, photoUrl: P.wok },
      { sectionId: "desserts", name: "Hotteok", description: "Sweet-filled Korean pancake, cinnamon, peanut.", price: 18, photoUrl: P.pastry, tags: ["vegetarian"] },
      { sectionId: "desserts", name: "Bingsu", description: "Shaved milk ice, red bean, mochi, condensed milk.", price: 32, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Soju (bottle)", description: "Jinro Chamisul Fresh — the national spirit.", price: 32, photoUrl: P.cocktail, tags: ["popular"] },
      { sectionId: "drinks", name: "Makgeolli (pot)", description: "Milky rice wine, served cold.", price: 28 },
      { sectionId: "drinks", name: "Cass Fresh", description: "Korean lager.", price: 18, photoUrl: P.beer },
      { sectionId: "drinks", name: "Peach soju", description: "Flavoured, sweet, easy.", price: 28 },
    ],
  ),

  "taqueria-mexico": makeMenu(
    "16",
    "Three tacos per order. Salsa verde made fresh. Mezcal when you're ready.",
    [
      { id: "antojitos", name: "Antojitos", intro: "Little cravings. Start here." },
      { id: "tacos", name: "Tacos", intro: "Three per order, handheld, unfussy." },
      { id: "mains", name: "Mains", intro: "When tacos aren't enough." },
      { id: "postres", name: "Postres", intro: "Dulce, caramelo, leche." },
      { id: "bebidas", name: "Bebidas", intro: drinksIntros.mx },
    ],
    [
      { sectionId: "antojitos", name: "Guacamole con totopos", description: "Hass avocado, lime, coriander, warm tortilla chips.", price: 28, photoUrl: P.bruschetta, tags: ["vegan", "vegetarian", "popular"] },
      { sectionId: "antojitos", name: "Queso fundido", description: "Melted Oaxaca cheese, chorizo, warm tortillas.", price: 32, photoUrl: P.plated, tags: ["spicy"] },
      { sectionId: "antojitos", name: "Elote", description: "Grilled corn, mayo, cotija cheese, chilli, lime.", price: 20, tags: ["vegetarian", "popular"] },
      { sectionId: "antojitos", name: "Nachos supreme", description: "Tortilla chips, refried beans, jalapeño, sour cream, guacamole.", price: 30, tags: ["vegetarian"] },
      { sectionId: "tacos", name: "Tacos al pastor (3pc)", description: "Spit-roasted pork marinated in adobo, pineapple, onion, coriander.", price: 34, photoUrl: P.asian, tags: ["popular", "chef-pick"] },
      { sectionId: "tacos", name: "Tacos de carnitas (3pc)", description: "Slow-cooked pork, pickled onion, salsa verde.", price: 32, photoUrl: P.asian, tags: ["popular"] },
      { sectionId: "tacos", name: "Tacos de barbacoa (3pc)", description: "Slow-braised lamb, onion, coriander, consommé on the side.", price: 36, photoUrl: P.stew, tags: ["chef-pick"] },
      { sectionId: "tacos", name: "Tacos de pescado (3pc)", description: "Beer-battered fish, cabbage, chipotle mayo, lime.", price: 34, tags: ["spicy"] },
      { sectionId: "tacos", name: "Tacos vegetarianos (3pc)", description: "Roasted mushroom, grilled corn, black bean, cotija.", price: 30, tags: ["vegetarian"] },
      { sectionId: "mains", name: "Burrito grande", description: "Flour tortilla, rice, beans, meat of choice, cheese, salsa.", price: 42, photoUrl: P.wok },
      { sectionId: "mains", name: "Enchiladas verdes", description: "Tortillas, chicken, salsa verde, crema, queso fresco.", price: 42, tags: ["spicy"] },
      { sectionId: "mains", name: "Chicken quesadilla", description: "Folded flour tortilla, chicken, cheese, pico de gallo.", price: 38 },
      { sectionId: "postres", name: "Churros con cajeta", description: "Warm churros, cajeta (goat-milk caramel).", price: 20, photoUrl: P.pastry, tags: ["vegetarian", "popular"] },
      { sectionId: "postres", name: "Flan de cajeta", description: "Silky caramel custard.", price: 18, photoUrl: P.dessertPlated, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "postres", name: "Tres leches", description: "Sponge soaked in three milks, whipped cream.", price: 22, tags: ["vegetarian"] },
      { sectionId: "bebidas", name: "Margarita clásica", description: "Tequila, lime, triple sec, salt rim.", price: 34, photoUrl: P.cocktail, tags: ["popular"] },
      { sectionId: "bebidas", name: "Mezcal (50ml)", description: "Artisanal smoky mezcal, orange slice.", price: 42, tags: ["chef-pick"] },
      { sectionId: "bebidas", name: "Paloma", description: "Tequila, grapefruit soda, salt rim.", price: 32, photoUrl: P.cocktail },
      { sectionId: "bebidas", name: "Michelada", description: "Mexican beer, lime, chilli, salt.", price: 22, tags: ["spicy"] },
      { sectionId: "bebidas", name: "Corona Extra", description: "Cold, with lime.", price: 18, photoUrl: P.beer },
      { sectionId: "bebidas", name: "Horchata", description: "Rice-cinnamon milk.", price: 16 },
    ],
  ),

  "balkan-grill": makeMenu(
    "20",
    "Roštilj first, everything else second. Rakija before, rakija after.",
    [
      { id: "predjela", name: "Predjela", intro: "To start — spreads, cheeses, and the bread that holds them." },
      { id: "rostilj", name: "Roštilj", intro: "From the charcoal grill. Always from the grill." },
      { id: "glavna", name: "Glavna jela", intro: "Beyond the grill — stews, rolls, slow food." },
      { id: "dezerti", name: "Dezerti", intro: "Sweet, creamy, or syrup-drenched." },
      { id: "drinks", name: "Pića", intro: drinksIntros.bk },
    ],
    [
      { sectionId: "predjela", name: "Kajmak", description: "Clotted cream cheese with warm bread and roasted red pepper.", price: 22, photoUrl: P.plated, tags: ["vegetarian", "gluten-free"] },
      { sectionId: "predjela", name: "Ajvar", description: "Roasted red pepper & aubergine relish, grilled bread.", price: 18, photoUrl: P.bruschetta, tags: ["vegan", "vegetarian"] },
      { sectionId: "predjela", name: "Urnebes salata", description: "Spicy sheep-cheese spread, crusty bread.", price: 20, tags: ["spicy", "vegetarian"] },
      { sectionId: "predjela", name: "Proja", description: "Cornbread with cheese and spinach.", price: 16, tags: ["vegetarian"] },
      { sectionId: "rostilj", name: "Ćevapi (10pc)", description: "Ten grilled minced-meat fingers, raw onion, somun bread, kajmak.", price: 42, photoUrl: P.mici, tags: ["popular", "chef-pick"] },
      { sectionId: "rostilj", name: "Pljeskavica", description: "Grilled Balkan burger patty (beef & lamb), ajvar, onion.", price: 38, photoUrl: P.mici, tags: ["popular"] },
      { sectionId: "rostilj", name: "Karađorđeva šnicla", description: "Stuffed veal escalope with kajmak, breaded and fried.", price: 52, photoUrl: P.steak, tags: ["chef-pick"] },
      { sectionId: "rostilj", name: "Ražnjići", description: "Pork skewers marinated overnight, grilled rare.", price: 36 },
      { sectionId: "rostilj", name: "Mešano meso", description: "Mixed grill — ćevapi, pljeskavica, ražnjići, sausage.", price: 68, photoUrl: P.mici, tags: ["chef-pick"] },
      { sectionId: "glavna", name: "Sarma", description: "Sour-cabbage rolls stuffed with pork & rice.", price: 38, photoUrl: P.sarmale, tags: ["popular"] },
      { sectionId: "glavna", name: "Pasulj", description: "Thick bean stew with smoked sausage.", price: 32, photoUrl: P.stew },
      { sectionId: "glavna", name: "Goulash", description: "Slow-cooked beef, paprika, onion, bread dumplings.", price: 42, photoUrl: P.stew, tags: ["spicy"] },
      { sectionId: "dezerti", name: "Palačinke", description: "Thin pancakes with walnut and chocolate.", price: 18, photoUrl: P.pastry, tags: ["vegetarian"] },
      { sectionId: "dezerti", name: "Krempita", description: "Vanilla-custard slice between flaky pastry.", price: 16, tags: ["vegetarian"] },
      { sectionId: "dezerti", name: "Tulumbe", description: "Fried syrup-soaked pastries.", price: 14, tags: ["vegetarian"] },
      { sectionId: "drinks", name: "Rakija (šljivovica)", description: "Plum brandy, 45%, served cold.", price: 16 },
      { sectionId: "drinks", name: "Vranac (glass)", description: "Montenegrin red — big, dark, spicy.", price: 28, photoUrl: P.wineRed },
      { sectionId: "drinks", name: "Jelen pivo", description: "Serbian lager.", price: 14, photoUrl: P.beer },
      { sectionId: "drinks", name: "Žilavka (glass)", description: "Herzegovinian white, dry, herbal.", price: 26 },
      { sectionId: "drinks", name: "Turkish coffee", description: "Served with lokum.", price: 10, photoUrl: P.espresso },
    ],
  ),
};

export function getMenu(slug: string): Menu | null {
  return menus[slug] ?? null;
}

export function hasMenu(slug: string): boolean {
  return slug in menus;
}
