import type { Restaurant } from "@/lib/types";

const restaurants: Restaurant[] = [
  {
    id: "1",
    slug: "casa-veche",
    name: "Casa Veche",
    cuisine: "Romanian",
    priceLevel: 2,
    zone: "Centru Vechi",
    city: "București",
    rating: 4.7,
    voteCount: 312,
    photoUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=600&h=400&fit=crop",
    photoCount: 24,
    status: "open",
    closesAt: "23:00",
    availableSlots: ["19:00", "19:30", "20:00", "20:30", "21:00"],
    reviewSnippet: "Best sarmale in town",
    topDimensionLabel: "food",
    topDimensionPercent: 94,
    distance: "0.3 km",
  },
  {
    id: "2",
    slug: "sakura-sushi",
    name: "Sakura Sushi",
    cuisine: "Japanese",
    priceLevel: 3,
    zone: "Dorobanți",
    city: "București",
    rating: 4.8,
    voteCount: 528,
    photoUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600&h=400&fit=crop",
    photoCount: 42,
    status: "open",
    closesAt: "22:30",
    availableSlots: ["19:00", "20:00", "21:00"],
    reviewSnippet: "Freshest fish outside Japan",
    topDimensionLabel: "quality",
    topDimensionPercent: 96,
    distance: "1.2 km",
  },
  {
    id: "3",
    slug: "trattoria-roma",
    name: "Trattoria Roma",
    cuisine: "Italian",
    priceLevel: 3,
    zone: "Herăstrău",
    city: "București",
    rating: 4.6,
    voteCount: 245,
    photoUrl: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&h=400&fit=crop",
    photoCount: 18,
    status: "open",
    closesAt: "23:30",
    availableSlots: ["19:30", "20:00", "20:30"],
    reviewSnippet: "Authentic pasta, great wine list",
    topDimensionLabel: "ambiance",
    topDimensionPercent: 91,
    distance: "2.1 km",
  },
  {
    id: "4",
    slug: "sultan-kebab",
    name: "Sultan Kebab",
    cuisine: "Turkish",
    priceLevel: 1,
    zone: "Obor",
    city: "București",
    rating: 4.3,
    voteCount: 189,
    photoUrl: null,
    photoCount: 0,
    status: "open",
    closesAt: "22:00",
    availableSlots: ["18:00", "18:30", "19:00", "19:30", "20:00", "20:30"],
    distance: "0.8 km",
  },
  {
    id: "5",
    slug: "le-bistrot",
    name: "Le Bistrot",
    cuisine: "French",
    priceLevel: 4,
    zone: "Aviatorilor",
    city: "București",
    rating: 4.9,
    voteCount: 412,
    photoUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&h=400&fit=crop",
    photoCount: 56,
    status: "closed",
    opensAt: "18:00",
    availableSlots: [],
    reviewSnippet: "Michelin-worthy experience",
    topDimensionLabel: "service",
    topDimensionPercent: 97,
    distance: "3.4 km",
  },
  {
    id: "6",
    slug: "dim-sum-house",
    name: "Dim Sum House",
    cuisine: "Chinese",
    priceLevel: 2,
    zone: "Piața Romană",
    city: "București",
    rating: 4.4,
    voteCount: 156,
    photoUrl: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&h=400&fit=crop",
    photoCount: 15,
    status: "open",
    closesAt: "21:30",
    availableSlots: ["19:00", "19:30"],
    distance: "1.5 km",
  },
  {
    id: "7",
    slug: "el-toro-tapas",
    name: "El Toro Tapas",
    cuisine: "Spanish",
    priceLevel: 2,
    zone: "Floreasca",
    city: "București",
    rating: 4.5,
    voteCount: 203,
    photoUrl: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?w=600&h=400&fit=crop",
    photoCount: 31,
    status: "open",
    closesAt: "00:00",
    availableSlots: ["20:00", "20:30", "21:00", "21:30"],
    reviewSnippet: "Amazing tapas and sangria",
    topDimensionLabel: "food",
    topDimensionPercent: 89,
    distance: "1.8 km",
  },
  {
    id: "8",
    slug: "maharaja-palace",
    name: "Maharaja Palace",
    cuisine: "Indian",
    priceLevel: 2,
    zone: "Universitate",
    city: "București",
    rating: 4.2,
    voteCount: 134,
    photoUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=600&h=400&fit=crop",
    photoCount: 12,
    status: "closed",
    opensAt: "17:00",
    availableSlots: [],
    distance: "0.5 km",
  },
  {
    id: "9",
    slug: "garden-grill",
    name: "Garden Grill",
    cuisine: "American",
    priceLevel: 2,
    zone: "Băneasa",
    city: "București",
    rating: 4.1,
    voteCount: 98,
    photoUrl: "https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=400&fit=crop",
    photoCount: 8,
    status: "open",
    closesAt: "22:00",
    availableSlots: ["18:00", "19:00", "20:00"],
    reviewSnippet: "Juiciest burgers in the city",
    topDimensionLabel: "food",
    topDimensionPercent: 85,
    distance: "4.2 km",
  },
  {
    id: "10",
    slug: "mezze-bar",
    name: "Mezze Bar",
    cuisine: "Lebanese",
    priceLevel: 2,
    zone: "Centru Vechi",
    city: "București",
    rating: 4.6,
    voteCount: 267,
    photoUrl: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&h=400&fit=crop",
    photoCount: 22,
    status: "open",
    closesAt: "23:00",
    availableSlots: ["19:00", "20:00", "21:00", "22:00"],
    reviewSnippet: "Hummus to die for",
    topDimensionLabel: "food",
    topDimensionPercent: 92,
    distance: "0.4 km",
  },
  {
    id: "11",
    slug: "pizzeria-napoli",
    name: "Pizzeria Napoli",
    cuisine: "Italian",
    priceLevel: 1,
    zone: "Tineretului",
    city: "București",
    rating: 4.3,
    voteCount: 321,
    photoUrl: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&h=400&fit=crop",
    photoCount: 19,
    status: "open",
    closesAt: "23:00",
    availableSlots: ["18:30", "19:00", "19:30", "20:00"],
    distance: "2.5 km",
  },
  {
    id: "12",
    slug: "brasserie-moderne",
    name: "Brasserie Moderne",
    cuisine: "French",
    priceLevel: 4,
    zone: "Primăverii",
    city: "București",
    rating: 4.7,
    voteCount: 178,
    photoUrl: null,
    photoCount: 0,
    status: "closed",
    opensAt: "19:00",
    availableSlots: [],
    reviewSnippet: "Exquisite fine dining",
    topDimensionLabel: "ambiance",
    topDimensionPercent: 95,
    distance: "3.0 km",
  },
  {
    id: "13",
    slug: "wok-express",
    name: "Wok Express",
    cuisine: "Thai",
    priceLevel: 1,
    zone: "Militari",
    city: "București",
    rating: 3.9,
    voteCount: 87,
    photoUrl: "https://images.unsplash.com/photo-1569562211093-4ed0d0758f12?w=600&h=400&fit=crop",
    photoCount: 6,
    status: "open",
    closesAt: "21:00",
    availableSlots: ["18:00", "18:30"],
    distance: "5.1 km",
  },
  {
    id: "14",
    slug: "taverna-greceasca",
    name: "Taverna Grecească",
    cuisine: "Greek",
    priceLevel: 2,
    zone: "Centru Vechi",
    city: "București",
    rating: 4.5,
    voteCount: 215,
    photoUrl: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&h=400&fit=crop",
    photoCount: 27,
    status: "open",
    closesAt: "23:00",
    availableSlots: ["19:00", "19:30", "20:00", "20:30", "21:00"],
    reviewSnippet: "Transport yourself to Santorini",
    topDimensionLabel: "ambiance",
    topDimensionPercent: 90,
    distance: "0.6 km",
  },
  {
    id: "15",
    slug: "seoul-kitchen",
    name: "Seoul Kitchen",
    cuisine: "Korean",
    priceLevel: 2,
    zone: "Dorobanți",
    city: "București",
    rating: 4.4,
    voteCount: 142,
    photoUrl: "https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=600&h=400&fit=crop",
    photoCount: 14,
    status: "open",
    closesAt: "22:00",
    availableSlots: ["19:00", "20:00", "21:00"],
    reviewSnippet: "Best Korean BBQ experience",
    topDimensionLabel: "food",
    topDimensionPercent: 88,
    distance: "1.3 km",
  },
  {
    id: "16",
    slug: "taqueria-mexico",
    name: "Taqueria Mexico",
    cuisine: "Mexican",
    priceLevel: 1,
    zone: "Obor",
    city: "București",
    rating: 4.0,
    voteCount: 76,
    photoUrl: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&h=400&fit=crop",
    photoCount: 9,
    status: "closed",
    opensAt: "17:30",
    availableSlots: [],
    distance: "0.9 km",
  },
  {
    id: "17",
    slug: "golden-dragon",
    name: "Golden Dragon",
    cuisine: "Chinese",
    priceLevel: 3,
    zone: "Herăstrău",
    city: "București",
    rating: 4.1,
    voteCount: 109,
    photoUrl: null,
    photoCount: 0,
    status: "open",
    closesAt: "22:30",
    availableSlots: ["19:00", "20:00", "21:00"],
    distance: "2.3 km",
  },
  {
    id: "18",
    slug: "la-mama",
    name: "La Mama",
    cuisine: "Romanian",
    priceLevel: 2,
    zone: "Piața Romană",
    city: "București",
    rating: 4.8,
    voteCount: 489,
    photoUrl: "https://images.unsplash.com/photo-1466978913421-dad2ebd01d17?w=600&h=400&fit=crop",
    photoCount: 38,
    status: "open",
    closesAt: "23:30",
    availableSlots: ["19:30", "20:00", "20:30", "21:00"],
    reviewSnippet: "Like eating at grandma's house",
    topDimensionLabel: "food",
    topDimensionPercent: 95,
    distance: "1.0 km",
  },
  {
    id: "19",
    slug: "ristorante-milano",
    name: "Ristorante Milano",
    cuisine: "Italian",
    priceLevel: 4,
    zone: "Aviatorilor",
    city: "București",
    rating: 4.6,
    voteCount: 198,
    photoUrl: "https://images.unsplash.com/photo-1550966871-3ed3cdb51f3a?w=600&h=400&fit=crop",
    photoCount: 33,
    status: "open",
    closesAt: "23:00",
    availableSlots: ["20:00", "20:30"],
    reviewSnippet: "Truffle pasta is a must",
    topDimensionLabel: "food",
    topDimensionPercent: 93,
    distance: "3.2 km",
  },
  {
    id: "20",
    slug: "balkan-grill",
    name: "Balkan Grill",
    cuisine: "Balkan",
    priceLevel: 1,
    zone: "Pantelimon",
    city: "București",
    rating: 3.8,
    voteCount: 64,
    photoUrl: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&h=400&fit=crop",
    photoCount: 5,
    status: "open",
    closesAt: "21:30",
    availableSlots: ["18:00", "19:00", "20:00"],
    distance: "6.0 km",
  },
];

export function getRestaurants(): Restaurant[] {
  return restaurants;
}

export function getTrendingRestaurants(): Restaurant[] {
  return [...restaurants].sort((a, b) => b.rating - a.rating).slice(0, 8);
}

export function getNewRestaurants(): Restaurant[] {
  return restaurants.slice(0, 4);
}

export function getOpenNowRestaurants(): Restaurant[] {
  return restaurants.filter((r) => r.status === "open");
}
