/**
 * Idempotent seed for the 11 supporting demo restaurants. Re-running drops
 * everything matching @tavli-supporting.invalid (auth users + restaurants
 * via cascade) and re-inserts cleanly from the spec file.
 *
 * Photos are intentionally NOT seeded here — those will be generated by
 * `scripts/generate-supporting-photos.ts` (separate run, costs Replicate
 * credits).
 */
import { config } from "dotenv";
config({ path: ".env.prod" });
import { createClient } from "@supabase/supabase-js";
import crypto from "node:crypto";
import { SUPPORTING_RESTAURANTS } from "./data/supporting-restaurants";

const CITY_SLUG = "bucuresti";
const OWNER_EMAIL_SUFFIX = "@tavli-supporting.invalid";
const REVIEW_EMAIL_DOMAIN = "tavli-supporting-reviews.invalid";
const OWNER_PASSWORD = process.env.SUPPORTING_OWNER_PASSWORD ?? "Tavli2026!supporting";

const ROMANIAN_WEEK: { dow: number; name: string }[] = [
  { dow: 1, name: "Luni" },
  { dow: 2, name: "Marți" },
  { dow: 3, name: "Miercuri" },
  { dow: 4, name: "Joi" },
  { dow: 5, name: "Vineri" },
  { dow: 6, name: "Sâmbătă" },
  { dow: 0, name: "Duminică" },
];

function snakeTag(tag: string): string {
  return tag.replace(/-/g, "_");
}

interface ScheduleDay { dayOfWeek: number; openTime: string; closeTime: string }

function toMins(hhmm: string): number {
  const [h, m] = hhmm.split(":").map(Number);
  return h * 60 + m;
}

function fromMins(mins: number): string {
  const hh = String(Math.floor(mins / 60)).padStart(2, "0");
  const mm = String(mins % 60).padStart(2, "0");
  return `${hh}:${mm}:00`;
}

/**
 * The reservations_check_capacity trigger uses `slot_end > reservation_time`,
 * so a slot stored as 18:00–02:00 (next day) never matches. We cap such
 * midnight-crossing slots at 23:59 in restaurant_availability — display
 * schedule keeps the original close time.
 */
function dbSlotEnd(start: string, end: string): string {
  return toMins(end) <= toMins(start) ? "23:59:00" : `${end}:00`;
}

/**
 * Find a reservation date/time that satisfies the trigger:
 *   slot_start <= time AND slot_end > time, on a day the restaurant is open.
 * Walks back from `today - daysAgo` up to 7 days to land on an open day.
 */
function pickReservationContext(
  availability: { dayOfWeek: number; startTime: string; endTime: string }[],
  daysAgo: number,
): { date: string; time: string } {
  const target = new Date();
  target.setDate(target.getDate() - daysAgo);
  for (let off = 0; off < 7; off++) {
    const d = new Date(target);
    d.setDate(d.getDate() - off);
    const dow = d.getDay();
    const slot = availability.find((a) => a.dayOfWeek === dow);
    if (!slot) continue;
    const startMins = toMins(slot.startTime);
    let endMins = toMins(slot.endTime);
    if (endMins <= startMins) endMins = 23 * 60 + 59; // cap midnight-crossing
    const pickMins = Math.min(startMins + 60, endMins - 30);
    return { date: d.toISOString().slice(0, 10), time: fromMins(pickMins) };
  }
  throw new Error(`no open day in week-before daysAgo=${daysAgo}`);
}

function buildScheduleDisplay(open: ScheduleDay[]): { days: string; hours: string }[] {
  const byDow = new Map<number, string>();
  for (const d of open) byDow.set(d.dayOfWeek, `${d.openTime} – ${d.closeTime}`);

  const rows: { days: string; hours: string }[] = [];
  let groupStart = 0;
  while (groupStart < ROMANIAN_WEEK.length) {
    const hours = byDow.get(ROMANIAN_WEEK[groupStart].dow) ?? "Închis";
    let groupEnd = groupStart;
    while (
      groupEnd + 1 < ROMANIAN_WEEK.length &&
      (byDow.get(ROMANIAN_WEEK[groupEnd + 1].dow) ?? "Închis") === hours
    ) {
      groupEnd += 1;
    }
    const days =
      groupStart === groupEnd
        ? ROMANIAN_WEEK[groupStart].name
        : `${ROMANIAN_WEEK[groupStart].name} – ${ROMANIAN_WEEK[groupEnd].name}`;
    rows.push({ days, hours });
    groupStart = groupEnd + 1;
  }
  return rows;
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("Supabase env vars missing");

  const admin = createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  // 1. Resolve city
  const { data: city, error: cityErr } = await admin
    .from("cities")
    .select("id")
    .eq("slug", CITY_SLUG)
    .maybeSingle();
  if (cityErr || !city) throw cityErr ?? new Error(`city not found: ${CITY_SLUG}`);

  // 2. Cleanup: drop restaurants → cascades menu/items/availability/reservations/reviews/photos.
  console.log("→ cleanup: dropping existing supporting restaurants…");
  const { error: delRestErr } = await admin
    .from("restaurants")
    .delete()
    .like("email", `%${OWNER_EMAIL_SUFFIX}`);
  if (delRestErr) throw delRestErr;

  // 3. Cleanup: drop auth users (cascades to profiles via FK).
  const { data: usersList, error: listErr } = await admin.auth.admin.listUsers({
    page: 1,
    perPage: 1000,
  });
  if (listErr) throw listErr;
  const supportingUsers = usersList.users.filter((u) =>
    u.email?.endsWith(OWNER_EMAIL_SUFFIX),
  );
  for (const u of supportingUsers) {
    const { error: dErr } = await admin.auth.admin.deleteUser(u.id);
    if (dErr) console.warn(`  · failed to delete ${u.email}: ${dErr.message}`);
  }
  console.log(`  · deleted ${supportingUsers.length} auth users + cascaded profiles`);

  // 4. Seed each restaurant
  for (const spec of SUPPORTING_RESTAURANTS) {
    console.log(`\n→ seeding ${spec.name} (${spec.slug})…`);

    // 4a. Auth user
    const { data: userData, error: userErr } = await admin.auth.admin.createUser({
      email: spec.ownerEmail,
      password: OWNER_PASSWORD,
      email_confirm: true,
      user_metadata: { full_name: `${spec.name} Owner (demo)` },
    });
    if (userErr || !userData.user) throw userErr ?? new Error("createUser returned no user");
    const userId = userData.user.id;

    // 4b. Profile (the on_auth_user_created trigger seeds id+email; we set role + name)
    const { error: profileErr } = await admin
      .from("profiles")
      .upsert(
        {
          id: userId,
          email: spec.ownerEmail,
          full_name: `${spec.name} Owner (demo)`,
          role: "restaurant_owner",
        },
        { onConflict: "id" },
      );
    if (profileErr) throw profileErr;

    // 4c. Restaurant — created_at backdated so "newest" feed sorts by spec age.
    const createdAt = new Date();
    createdAt.setDate(createdAt.getDate() - spec.daysAgoCreated);
    const scheduleDisplay = buildScheduleDisplay(spec.schedule);

    const { data: rest, error: restErr } = await admin
      .from("restaurants")
      .insert({
        slug: spec.slug,
        name: spec.name,
        cuisines: spec.cuisines,
        city_id: city.id,
        zone: spec.zone,
        price_level: spec.priceLevel,
        lat: spec.lat,
        lng: spec.lng,
        description: spec.description,
        hero_note: spec.heroNote,
        address: spec.address,
        email: spec.ownerEmail,
        tags: spec.bestFor,
        schedule: scheduleDisplay,
        status: "live",
        owner_user_id: userId,
        created_at: createdAt.toISOString(),
      })
      .select("id")
      .single();
    if (restErr || !rest) throw restErr ?? new Error("restaurant insert returned nothing");

    // 4d. Menu (single row per restaurant)
    const { error: menuErr } = await admin.from("menus").insert({
      restaurant_id: rest.id,
      currency: "lei",
      hero_note: spec.menu.heroNote,
    });
    if (menuErr) throw menuErr;

    // 4e. Sections — collect spec-id → real-uuid mapping for items below.
    const sectionIdMap = new Map<string, string>();
    for (const sec of spec.menu.sections) {
      const { data: secRow, error: secErr } = await admin
        .from("menu_sections")
        .insert({
          restaurant_id: rest.id,
          name: sec.name,
          intro: sec.intro,
          sort_order: sec.orderIndex,
        })
        .select("id")
        .single();
      if (secErr || !secRow) throw secErr ?? new Error("section insert returned nothing");
      sectionIdMap.set(sec.id, secRow.id);
    }

    // 4f. Items — kebab-case tags → snake_case for the DB enum.
    const itemRows = spec.menu.items.map((item, idx) => {
      const sectionId = sectionIdMap.get(item.sectionId);
      if (!sectionId) {
        throw new Error(`unknown sectionId "${item.sectionId}" in ${spec.slug}`);
      }
      return {
        restaurant_id: rest.id,
        section_id: sectionId,
        name: item.name,
        description: item.description,
        price_cents: item.priceLei * 100,
        currency: "lei" as const,
        dietary_tags: item.tags.map(snakeTag),
        is_chef_pick: item.tags.includes("chef-pick"),
        is_available: true,
        sort_order: idx,
      };
    });
    const { error: iErr } = await admin.from("menu_items").insert(itemRows);
    if (iErr) throw iErr;

    // 4g. Availability — slot_end capped at 23:59 if it would cross midnight,
    //      so the capacity-check trigger's `slot_end > time` predicate works.
    const availRows = spec.availability.map((a) => ({
      restaurant_id: rest.id,
      day_of_week: a.dayOfWeek,
      slot_start: `${a.startTime}:00`,
      slot_end: dbSlotEnd(a.startTime, a.endTime),
      capacity: a.capacity,
    }));
    const { error: aErr } = await admin.from("restaurant_availability").insert(availRows);
    if (aErr) throw aErr;

    // 4h. Reservations + reviews — every review needs a backing reservation.
    //      Pick a (date, time) within the spec's availability so the capacity
    //      trigger doesn't reject. Reviews trigger recomputes rating + vote_count.
    for (const r of spec.reviews) {
      const ctx = pickReservationContext(spec.availability, r.daysAgo);
      const guestEmail = `${r.firstName.toLowerCase()}-${spec.slug}-${r.daysAgo}@${REVIEW_EMAIL_DOMAIN}`;

      const { data: reservation, error: rErr } = await admin
        .from("reservations")
        .insert({
          restaurant_id: rest.id,
          guest_name: `${r.firstName} (seed)`,
          guest_phone: "0700000000",
          guest_email: guestEmail,
          party_size: r.partySize,
          reservation_date: ctx.date,
          reservation_time: ctx.time,
          zone: r.zone ?? null,
          status: "completed",
          confirmation_token: crypto.randomBytes(32).toString("hex"),
        })
        .select("id")
        .single();
      if (rErr || !reservation) throw rErr ?? new Error("reservation insert returned nothing");

      const { error: revErr } = await admin.from("reviews").insert({
        reservation_id: reservation.id,
        restaurant_id: rest.id,
        rating: r.rating,
        comment: r.comment,
        first_name: r.firstName,
        party_size: r.partySize,
        reservation_date: ctx.date,
      });
      if (revErr) throw revErr;
    }

    console.log(
      `  ✓ ${spec.menu.sections.length} sections · ${spec.menu.items.length} items · ${spec.availability.length} availability rows · ${spec.reviews.length} reviews`,
    );
  }

  console.log(`\n— ${SUPPORTING_RESTAURANTS.length} supporting restaurants seeded —`);
  console.log(`  discovery:   https://tavli.ro/${CITY_SLUG}\n`);
}

main().catch((err) => {
  console.error("seed-supporting-restaurants failed:", err);
  process.exit(1);
});
